import { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { api } from '@/lib/api';
import { RA_PREPAID_ERROR } from '@/lib/agentBilling';
interface Card {attach:(s:string)=>Promise<void>;destroy:()=>Promise<void>;tokenize:(d:object)=>Promise<{status:string;token?:string;details?:{card?:{prepaidType?:string}};errors?:{message:string}[]}>}
interface Square {payments:(a:string,l:string)=>{card:()=>Promise<Card>}}
interface Checkout {company:string;amountCents:number;purpose:string;reconciling?:boolean;paid:boolean;applicationId:string;locationId:string;sandbox:boolean;offline:boolean;email:string}
export default function AgentCheckout(){
 const [search]=useSearchParams(),kind=search.get('kind')??'',id=search.get('id')??'',token=search.get('token')??'';
 const endpoint=`/api/agent-checkout/${encodeURIComponent(kind)}/${encodeURIComponent(id)}?token=${encodeURIComponent(token)}`;
 const details=useQuery({queryKey:['agent-checkout',kind,id,token],queryFn:()=>api.get<Checkout>(endpoint),retry:false});
 const d=details.data,card=useRef<Card|null>(null),[ready,setReady]=useState(false),[consent,setConsent]=useState(false),[error,setError]=useState<string|null>(null),[fixture,setFixture]=useState('credit');
 useEffect(()=>{if(!d||d.paid||d.offline||d.reconciling)return;let active=true,owned:Card|null=null;
 const load=async()=>{const url=d.sandbox?'https://sandbox.web.squarecdn.com/v1/square.js':'https://web.squarecdn.com/v1/square.js';
 if(!(window as Window&{Square?:Square}).Square)await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src=url;script.onload=()=>resolve();script.onerror=()=>reject(new Error('Secure card entry could not load. Reload to retry.'));document.head.appendChild(script);});
 const square=(window as Window&{Square?:Square}).Square;if(!square)throw new Error('Secure card entry is unavailable.');owned=await square.payments(d.applicationId,d.locationId).card();if(!active){await owned.destroy();return;}await owned.attach('#square-agent-card');card.current=owned;setReady(true);};
 void load().catch(e=>{if(active)setError(String(e.message??e));});return()=>{active=false;card.current=null;if(owned)void owned.destroy();};},[d]);
 const payment=useMutation({mutationFn:async()=>{if(d?.reconciling)return api.post<{ok:boolean;redirect:string}>(endpoint,{resume:true});if(!d||!consent)throw new Error('Please agree before paying.');setError(null);let sourceId=`offline-${fixture}`;
 if(!d.offline){if(!card.current)throw new Error('Secure card entry is not ready.');const result=await card.current.tokenize({amount:(d.amountCents/100).toFixed(2),currencyCode:'USD',intent:d.purpose==='resignation'||d.purpose==='service_fee'?'CHARGE':'CHARGE_AND_STORE',customerInitiated:true,sellerKeyedIn:false,billingContact:{email:d.email,countryCode:'US'}});if(result.status!=='OK'||!result.token)throw new Error(result.errors?.map(e=>e.message).join(' ')||'Check your card details and try again.');if(d.purpose!=='resignation'&&result.details?.card?.prepaidType==='PREPAID')throw new Error(RA_PREPAID_ERROR);sourceId=result.token;}
 return api.post<{ok:boolean;redirect:string}>(endpoint,{sourceId,consent:true});},onSuccess:r=>window.location.assign(r.redirect),onError:(e:Error)=>setError(e.message)});
 return <main className="mx-auto max-w-xl px-5 py-12 space-y-5"><h1 className="font-display text-3xl">{d?.purpose==='resignation'?'Pay resignation charge':d?.purpose==='service_fee'?'Pay outstanding service fees':'Complete your payment'}</h1>
 {details.isLoading?<p>Loading payment details…</p>:details.isError?<p role="alert">{(details.error as Error).message}</p>:d?.paid?<p>This payment is complete. <a className="underline" href={kind==='order'?`/order/confirmed?ref=${id}`:'/portal'}>Continue</a></p>:d?.reconciling?<><p>A payment is being checked. Retry to check this same payment; we will not start a second charge.</p>{error?<p role="alert">{error}</p>:null}<Button disabled={payment.isPending} onClick={()=>payment.mutate()}>{payment.isPending?'Checking payment…':'Check payment result'}</Button></>:d?<><p>{d.company}</p><p className="text-xl">${(d.amountCents/100).toFixed(2)}</p><p>{d.purpose==='service_fee'?'This payment settles outstanding registered-agent service fees. It does not renew service or change the recorded resignation or appointment end date.':d.purpose==='resignation'?'State filing fees and processing. This does not purchase another year of registered-agent service.':'Your card is saved securely with Square for automatic annual renewal. We cannot provide registered-agent service without your agreement and a saved eligible card.'}</p>
 {d.offline?<label className="block">Offline test card<select aria-label="Offline test card" className="block border rounded p-2" value={fixture} onChange={e=>setFixture(e.target.value)}><option value="credit">Credit card</option><option value="prepaid">Prepaid card</option><option value="wallet">Cannot save</option><option value="decline">Declined card</option></select></label>:<div id="square-agent-card"/>}
 <label className="flex gap-3 items-start"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="Agree to payment"/><span>{d.purpose==='service_fee'?`I authorize payment of $${(d.amountCents/100).toFixed(2)} toward the outstanding registered-agent service fees shown above.`:d.purpose==='resignation'?'I authorize this resignation charge.':'I authorize this payment, automatic annual renewal and storing my card with Square under the Terms of Service.'}</span></label>
 {error?<p role="alert" className="text-destructive">{error}</p>:null}<Button disabled={!consent||(!d.offline&&!ready)||payment.isPending} onClick={()=>payment.mutate()}>{payment.isPending?'Checking payment…':'Pay now'}</Button><p className="text-sm text-muted-foreground">If payment is declined, you can try again or use another card immediately. Your bank may briefly show an authorization hold for an unsuccessful attempt.</p></>:null}</main>;
}
