/** Fault injection against audit coverage and the real ledger guard. No product writes. */
import { mkdtempSync, rmSync, writeFileSync, readFileSync, mkdirSync, copyFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { ROOT, git, ledgerRegressions, type Ledger } from "./ledger-lib";
import { CHECKS, hash, validateAudit, type AuditData, type Finding } from "./audit-session-lib";
import { intakeItems, type Intake } from "./audit-import-lib";
import { manifestFor } from "./audit-session";
import { renderList } from "./ledger-print";
const rows:{name:string;ok:boolean}[]=[];
function check(name:string,ok:boolean){rows.push({name,ok});console.log(`${ok?"PASS":"FAIL"} ${name}`);}
const ledger:Ledger={version:2,builtFrom:[],rulings:[],batches:[],items:[{id:"1",tag:"fixture",area:"Office",housekeeping:false,source:"fixture",text:"fixture source",verdict:"open",waitsOn:[],parts:[{key:"all",scope:"fixture",status:"open",waitsOn:[],history:[{at:"2026-01-01T00:00:00Z",event:"recorded"}]}]}]};
const commit="1".repeat(40),text="First sentence.\nSecond sentence.\n",artifactText=Buffer.from("Opened complete fixture source; expectation and observed result agree.");
const finding:Finding={key:"new-1",where:"Fixture screen",file:"fixture.ts",line:2,reads:"Second sentence.",claims:"Fixture claim",truth:"Fixture evidence",replacement:"Corrected sentence.",severity:"wording",relation:"new",evidence:["proof"],review:{reviewer:"independent-fixture-reviewer",evidence:"Reopened source and confirmed the defect; checked the replacement separately.",replacement:"correct",priorCompared:true}};
const base:AuditData={manifest:{schema:1,run:"fixture",commit,createdAt:"2026-01-01T00:00:00Z",files:[{path:"fixture.ts",lines:2,sha:hash(text),area:"office",bucket:1,scope:"product"}],excluded:[],priors:[{id:"1",part:"all",bucket:1,item:ledger.items[0]}],ledger,ledgerSha:hash(JSON.stringify(ledger)),rulingsText:"",buckets:1,requestedBuckets:1,obligations:[]},receipts:[{file:"fixture.ts",sha:hash(text),from:1,to:2,reader:"reader-1",chunkSha:hash(text.trimEnd())}],reports:[{bucket:1,commit,reader:"reader-1",files:[{path:"fixture.ts",lines:2,sha:hash(text),noFindings:false}],priorFindings:[{id:"1",part:"all",status:"still open",evidence:"First sentence remains.",evidenceIds:["proof"]}],findings:[finding]}],evidence:[{id:"proof",commit,kind:"source",status:"verified",detail:"Read fixture source.",artifact:"evidence/source.txt",sha:hash(artifactText),checkedAt:"2026-01-01T00:00:00Z"}],checks:CHECKS.map(id=>({id,status:"verified",evidence:["proof"],detail:"Fixture requirement checked."}))};
const validate=(d:AuditData)=>validateAudit(d,p=>p==="fixture.ts"?text:null,p=>p==="evidence/source.txt"?artifactText:null);
check("complete evidence fixture passes",validate(base).problems.length===0);
function refuse(name:string,mutate:(d:AuditData)=>void,match:RegExp){const d=structuredClone(base);mutate(d);const r=validate(d);check(name,r.problems.some(p=>match.test(p)));}
refuse("short line count refused",d=>{d.reports[0].files[0].lines=1;},/exact file/);
refuse("overstated line count refused",d=>{d.reports[0].files[0].lines=3;},/exact file/);
refuse("non-number line count refused",d=>{d.reports[0].files[0].lines="2" as unknown as number;},/exact file/);
refuse("NaN line count refused",d=>{d.reports[0].files[0].lines=NaN;},/exact file/);
refuse("negative line count refused",d=>{d.reports[0].files[0].lines=-1;},/exact file/);
refuse("duplicate file refused",d=>{d.reports[0].files.push(d.reports[0].files[0]);},/duplicate file/);
refuse("missing file refused",d=>{d.reports[0].files=[];},/file unread/);
refuse("missing entire report refused",d=>{d.reports=[];},/bucket missing/);
refuse("wrong commit refused",d=>{d.reports[0].commit="2".repeat(40);},/invalid report/);
refuse("changed source hash refused",d=>{d.manifest.files[0].sha="0".repeat(64);},/source changed/);
refuse("wrong reader receipts refused",d=>{d.receipts[0].reader="another";},/receipts missing/);
refuse("unread first line refused",d=>{d.receipts[0].from=2;d.receipts[0].chunkSha=hash("Second sentence.");},/receipts missing/);
refuse("receipt tampering refused",d=>{d.receipts[0].chunkSha="0".repeat(64);},/receipt hash/);
refuse("every prior part required",d=>{d.reports[0].priorFindings=[];},/prior missing/);
refuse("duplicate prior refused",d=>{d.reports[0].priorFindings.push(d.reports[0].priorFindings[0]);},/duplicate prior/);
refuse("unknown prior refused",d=>{d.reports[0].priorFindings[0].id="fake";},/unexpected\/duplicate prior/);
refuse("not verified prior refuses completion",d=>{d.reports[0].priorFindings[0].status="not verified";},/not reconciled/);
refuse("manifest cannot omit a prior part",d=>{d.manifest.priors=[];},/every ledger part/);
refuse("retained decision requires quote",d=>{d.reports[0].priorFindings[0].status="retained by owner";},/lacks quoted owner/);
refuse("unknown duplicate target refused",d=>{d.reports[0].priorFindings[0].status="duplicate";d.reports[0].priorFindings[0].duplicate={id:"missing",part:"all"};},/invalid duplicate/);
refuse("false no-findings declaration refused",d=>{d.reports[0].files[0].noFindings=true;},/no-findings/);
refuse("quote at wrong line refused",d=>{d.reports[0].findings[0].line=1;},/quoted text/);
refuse("unknown source file refused",d=>{d.reports[0].findings[0].file="other.ts";},/outside assigned/);
refuse("unsupported severity refused",d=>{d.reports[0].findings[0].severity="critical" as never;},/invalid severity/);
refuse("finding rechecked by its author refused",d=>{d.reports[0].findings[0].review.reviewer="reader-1";},/independent recheck/);
refuse("missing prior comparison refused",d=>{d.reports[0].findings[0].review.priorCompared=false;},/independent recheck/);
refuse("missing replacement refused",d=>{d.reports[0].findings[0].replacement="";},/lacks replacement/);
refuse("duplicate defect with new key refused",d=>{d.reports[0].findings.push({...d.reports[0].findings[0],key:"new-2"});},/duplicate defect/);
refuse("missing checklist entry refused",d=>{d.checks.pop();},/required audit check/);
refuse("unverified source refuses completion",d=>{d.evidence[0].status="not verified";},/not verified/);
refuse("missing evidence bytes refused",d=>{d.evidence[0].artifact="evidence/missing";},/missing\/changed evidence/);
refuse("evidence hash mismatch refused",d=>{d.evidence[0].sha="0".repeat(64);},/missing\/changed evidence/);
refuse("evidence traversal refused",d=>{d.evidence[0].artifact="../outside";},/invalid artifact/);
refuse("evidence commit mismatch refused",d=>{d.evidence[0].commit="0".repeat(40);},/invalid evidence/);
refuse("runtime evidence needs offline proof",d=>{d.evidence[0].kind="runtime";},/offline isolation/);
refuse("statute check requires Sunshine source",d=>{d.manifest.obligations.push({id:"statute-605.0101",kind:"source",scope:"read law",targets:[]});d.checks.push({id:"statute-605.0101",status:"verified",evidence:["proof"],detail:"claim"});},/Online Sunshine/);
refuse("render obligation cannot use source evidence",d=>{d.manifest.obligations.push({id:"word-1",kind:"render",scope:"read rendered pages",targets:[]});d.checks.push({id:"word-1",status:"verified",evidence:["proof"],detail:"claim"});},/wrong evidence kind/);
refuse("render evidence requires every page",d=>{d.evidence[0].kind="render";d.evidence[0].expected="all pages";d.evidence[0].observed="one page";d.evidence[0].pages=2;d.evidence[0].pagesInspected=1;},/not every rendered page/);
refuse("comparison needs expected and observed text",d=>{d.evidence[0].kind="comparison";},/expected and observed/);
const good=structuredClone(base);good.receipts=[{...base.receipts[0],to:1,chunkSha:hash("First sentence.")},{...base.receipts[0],from:2,chunkSha:hash("Second sentence.")}];check("multiple complete read ranges pass",validate(good).problems.length===0);
const intake:Intake={schema:1,run:"fixture",commit,completedAt:"2026-01-01T00:00:00Z",manifestSha:hash("manifest"),auditSha:hash("audit"),findings:[finding]};
const path="docs/audit/intakes/fixture.json",raw=JSON.stringify(intake),after=structuredClone(ledger);after.auditImports=[{path,sha:hash(raw)}];after.items.push(...intakeItems(intake,path));
const read=(p:string)=>p===path?raw:null;
check("checked source appends open item without changing prior",ledgerRegressions(ledger,after,{read}).length===0&&JSON.stringify(after.items[0])===JSON.stringify(ledger.items[0])&&after.items[1].parts[0].status==="open");
function badImport(name:string,mutate:(a:Ledger)=>void,match:RegExp){const a=structuredClone(after);mutate(a);check(name,ledgerRegressions(ledger,a,{read}).some(p=>match.test(p)));}
badImport("unproven new record refused",a=>{delete a.auditImports;},/auditors never wrote/);
badImport("changed import hash refused",a=>{a.auditImports![0].sha="0".repeat(64);},/missing\/changed/);
badImport("edited imported finding refused",a=>{a.items[1].text="replacement invented";},/differs from source/);
badImport("removed prior item refused",a=>{a.items.shift();},/source record was removed/);
badImport("duplicate import ref refused",a=>{a.auditImports!.push(a.auditImports![0]);},/duplicate audit import reference/);
check("new intake cannot publish as records-only",ledgerRegressions(ledger,after,{read,strict:true}).some(p=>/never a records-only/.test(p)));
const erased=structuredClone(after);erased.auditImports=[];check("retained intake reference immutable",ledgerRegressions(after,erased,{read}).some(p=>/import history/.test(p)));
check("source loss detected on clean later ledger",ledgerRegressions(after,after,{read:()=>null}).some(p=>/missing\/changed/));
const duplicate=structuredClone(intake);duplicate.run="different-run";const raw2=JSON.stringify(duplicate);const dupAfter=structuredClone(after);dupAfter.auditImports!.push({path:"docs/audit/intakes/different-run.json",sha:hash(raw2)});dupAfter.items.push(...intakeItems(duplicate,"docs/audit/intakes/different-run.json"));check("same exact defect in another run refused",ledgerRegressions(after,dupAfter,{read:p=>p===path?raw:raw2}).some(p=>/duplicate imported defect/.test(p)));
const temp=mkdtempSync(join(tmpdir(),"audit-mechanism-check-"));
try{
 const dir=join(temp,"run"),cli=join(ROOT,"docs/audit/audit-session.ts");
 const run=(...args:string[])=>spawnSync("bun",[cli,...args],{cwd:ROOT,encoding:"utf8",maxBuffer:64*1024*1024});
 const initialized=run("init",dir,"real-command-fixture","HEAD","2");check("real init command succeeds",initialized.status===0);
 const m=JSON.parse(readFileSync(join(dir,"manifest.json"),"utf8"));
 check("actual current ledger has every part assigned",m.priors.length===m.ledger.items.reduce((n:number,i:{parts:unknown[]})=>n+i.parts.length,0));
 check("all eight masters and twelve Word outputs scheduled",m.obligations.filter((o:{id:string})=>o.id.startsWith("masters-")).length===28&&m.obligations.filter((o:{id:string})=>o.id.startsWith("word-")).length===12);
 const f=m.files.find((f:{lines:number})=>f.lines>0&&f.lines<300);const readResult=run("read",dir,"fixture-reader",f.path,"1",String(f.lines));check("real read command emits actual source and receipt",readResult.status===0&&readResult.stdout.includes(f.path));
 const incomplete=run("check",dir);check("real gate refuses empty reports and evidence",incomplete.status!==0&&incomplete.stderr.includes("prior missing"));
 const report=run("report",dir);check("partial report is explicitly incomplete",report.status!==0&&readFileSync(join(dir,"REPORT.md"),"utf8").includes("INCOMPLETE"));
 m.files.pop();writeFileSync(join(dir,"manifest.json"),JSON.stringify(m));const tampered=run("check",dir);check("real gate rejects altered manifest denominator",tampered.status!==0&&tampered.stderr.includes("manifest differs"));
 check("existing run never overwritten",run("init",dir,"real-command-fixture","HEAD","2").status!==0);
 const factory=manifestFor("factory",git(["rev-parse","HEAD"]).trim(),2);check("source inventory includes server and browser expectation checks",factory.files.some(f=>f.path==="webapp/server/e2e.ts")&&factory.files.some(f=>f.path==="webapp/scripts/behavioral.ts"));
  for (const rev of ["e630541", "fffd6567"]) check(`historical generated report remains identical at ${rev}`, renderList(JSON.parse(git(["show", `${rev}:docs/audit/ledger.json`]))) === git(["show", `${rev}:docs/audit/findings-open.md`]));
  // Real intake and guard commands in a tiny synthetic Git repository. The
  // fixture evidence below is deliberately simulated, never a product audit.
  const fixture=join(temp,"intake-repo");mkdirSync(join(fixture,"docs/audit"),{recursive:true});mkdirSync(join(fixture,"webapp/server"),{recursive:true});mkdirSync(join(fixture,"webapp/src"),{recursive:true});
  for(const name of ["audit-session-lib.ts","audit-session.ts","audit-import-lib.ts","audit-import.ts","ledger-lib.ts","evidence.ts","ledger-print.ts","inventory.ts","inventory-policy.json","guard.ts","audit-reader.md"])copyFileSync(join(ROOT,"docs/audit",name),join(fixture,"docs/audit",name));
  const env={...process.env,FPSLLC_BATCH:"",FPSLLC_HOME:join(temp,"owner"),GIT_AUTHOR_NAME:"audit fixture",GIT_AUTHOR_EMAIL:"fixture@example.invalid",GIT_COMMITTER_NAME:"audit fixture",GIT_COMMITTER_EMAIL:"fixture@example.invalid"};
  const cmd=(...args:string[])=>spawnSync(args[0],args.slice(1),{cwd:fixture,env,encoding:"utf8",maxBuffer:64*1024*1024});
  const must=(...args:string[])=>{const r=cmd(...args);if(r.status!==0)throw Error(r.stdout+r.stderr);return r.stdout.trim();};
  must("git","init","--quiet");writeFileSync(join(fixture,"webapp/server/fixture.ts"),text);writeFileSync(join(fixture,"webapp/vercel.json"),"{}\n");writeFileSync(join(fixture,"docs/audit/ledger.json"),JSON.stringify(ledger));writeFileSync(join(fixture,"docs/audit/rulings.md"),"# Synthetic fixture decisions\n");
  must("git","add","webapp/server/fixture.ts","webapp/vercel.json","docs/audit/ledger.json","docs/audit/rulings.md","docs/audit/inventory-policy.json");must("git","commit","--quiet","-m","synthetic audit fixture");
  const runDir=join(temp,"complete-fixture");must("bun","docs/audit/audit-session.ts","init",runDir,"intake-fixture","HEAD","1");
  const fm=JSON.parse(readFileSync(join(runDir,"manifest.json"),"utf8"));
  for(const f of fm.files)must("bun","docs/audit/audit-session.ts","read",runDir,"reader-1",f.path,String(f.lines?1:0),String(f.lines));
  writeFileSync(join(runDir,"evidence/source.txt"),artifactText);
  const fe=[{...base.evidence[0],commit:fm.commit},{...base.evidence[0],id:"runtime",commit:fm.commit,kind:"runtime",offline:true,expected:"Synthetic positive fixture",observed:"Synthetic positive fixture"},{...base.evidence[0],id:"render",commit:fm.commit,kind:"render",expected:"Synthetic page",observed:"Synthetic page",pages:1,pagesInspected:1}];
  writeFileSync(join(runDir,"evidence.json"),JSON.stringify(fe));
  const fc=JSON.parse(readFileSync(join(runDir,"checks.json"),"utf8")).map((c:{id:string})=>({...c,status:"verified",evidence:[c.id.startsWith("workflow-")?"runtime":c.id.startsWith("pdf-")?"render":"proof"],detail:"Synthetic harness attestation, not a product run"}));writeFileSync(join(runDir,"checks.json"),JSON.stringify(fc));
  writeFileSync(join(runDir,"bucket-1.json"),JSON.stringify({...base.reports[0],commit:fm.commit,files:fm.files.map((f:{path:string;lines:number;sha:string})=>({...f,noFindings:f.path!=="webapp/server/fixture.ts"})),findings:[{...finding,file:"webapp/server/fixture.ts"}]}));
  check("real completion gate accepts complete synthetic run",cmd("bun","docs/audit/audit-session.ts","check",runDir).status===0);
  const priorBytes=readFileSync(join(fixture,"docs/audit/ledger.json"),"utf8");
  check("real intake preview leaves ledger untouched",cmd("bun","docs/audit/audit-import.ts",runDir).status===0&&readFileSync(join(fixture,"docs/audit/ledger.json"),"utf8")===priorBytes);
  const applied=cmd("bun","docs/audit/audit-import.ts",runDir,"--apply");check("real intake applies verified open finding",applied.status===0);
  if(applied.status!==0)console.log(applied.stdout+applied.stderr);
  const imported=JSON.parse(readFileSync(join(fixture,"docs/audit/ledger.json"),"utf8"));check("real intake preserves prior records and leaves new work open",JSON.stringify(imported.items[0])===JSON.stringify(ledger.items[0])&&imported.items.length===2&&imported.items[1].parts[0].status==="open");
  const guarded=cmd("bun","docs/audit/guard.ts");check("real commit guard accepts exact retained intake",guarded.status===0);if(guarded.status!==0)console.log(guarded.stdout+guarded.stderr);
  check("real intake refuses importing a run twice",cmd("bun","docs/audit/audit-import.ts",runDir,"--apply").status!==0);
  const intakePath=join(fixture,"docs/audit/intakes/intake-fixture.json");writeFileSync(intakePath,readFileSync(intakePath,"utf8")+" ");const corrupted=cmd("bun","docs/audit/guard.ts");check("real guard refuses changed retained audit source",corrupted.status!==0&&corrupted.stderr.includes("intake missing/changed"));
}finally{rmSync(temp,{recursive:true,force:true});}
console.log(`${rows.filter(r=>r.ok).length}/${rows.length} audit mechanism checks passed; fixture evidence is not a product audit.`);
if(rows.some(r=>!r.ok))process.exitCode=1;
