import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
interface Agent {ra_resignation_reason?:string|null;ra_resignation_note?:string|null;ra_cancellation_requested_at?:string|null;ra_cancellation_note?:string|null;ra_appointment_date:string|null;ra_renewal_date:string|null;ra_replaced_at:string|null;ra_proof_note:string|null;ra_resignation_due:string|null;ra_resignation_submitted:string|null;ra_resignation_filed:string|null;ra_resignation_mailed:string|null;ra_resignation_emailed_at:string|null;ra_resignation_document:string|null;ra_ended_date:string|null}
export function AgentServicePanel({orderId}:{orderId:string}){
 const qc=useQueryClient(),q=useQuery({queryKey:['admin','agent',orderId],queryFn:()=>api.get<Agent>(`/api/admin/orders/${orderId}/agent`)});
 const [reason,setReason]=useState('timely-cancellation'),[action,setAction]=useState('appointment'),[date,setDate]=useState(''),[note,setNote]=useState(''),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState<string|null>(null);
 const refresh=()=>{qc.invalidateQueries({queryKey:['admin']});setMessage('Saved.');};
 const save=useMutation({mutationFn:()=>api.post(`/api/admin/orders/${orderId}/agent`,{action,date,note,reason}),onSuccess:refresh});
 const copy=useMutation({mutationFn:async()=>{const f=new FormData();if(file)f.set('file',file);const r=await fetch(`/api/admin/orders/${orderId}/agent-copy`,{method:'POST',body:f,credentials:'include'});const b=await r.json();if(!r.ok)throw new Error(b.error?.message||'Could not send copy.');},onSuccess:refresh});
 const d=q.data,day=(s:string|null|undefined)=>s?.slice(0,10)||'Not recorded';
 return <section className="space-y-3 rounded-xl border p-4 text-sm" data-testid="agent-service-panel"><h3 className="font-semibold">Registered-agent appointment and cancellation</h3>{q.isError?<p role="alert">Could not load the appointment. Retry opening this order.</p>:null}<p>Appointment effective: {day(d?.ra_appointment_date)}. Renewal: {day(d?.ra_renewal_date)}.</p>{d?.ra_cancellation_requested_at?<p>Cancellation received: {day(d.ra_cancellation_requested_at)}. {d.ra_cancellation_note}</p>:null}{d?.ra_replaced_at?<p>Replacement verified: {day(d.ra_replaced_at)}. {d.ra_proof_note}</p>:null}
 {d?.ra_resignation_due||d?.ra_resignation_submitted?<div className="border border-amber-300 bg-amber-50 text-amber-950 p-3"><strong>{d.ra_resignation_submitted?'Resignation submitted':`Resignation due ${day(d.ra_resignation_due)}`}</strong>{d.ra_resignation_note?<p>Supporting record: {d.ra_resignation_note}</p>:null}<p>Submit the resignation to the Division. Record submission and the state filing date separately. Email the PDF copy and promptly mail the statutory notice.</p><p>Submitted: {day(d.ra_resignation_submitted)} · State filed: {day(d.ra_resignation_filed)} · Appointment ends: {day(d.ra_ended_date)}</p><p>Email sent: {day(d.ra_resignation_emailed_at)} · Notice mailed: {day(d.ra_resignation_mailed)}</p></div>:null}
 <label className="block">Record an event<select aria-label="Agent event" className="block w-full rounded border p-2" value={action} onChange={e=>{setAction(e.target.value);setMessage(null);}}><option value="appointment">Appointment takes effect</option><option value="cancellation">Cancellation received by email</option><option value="replacement">Replacement agent verified</option><option value="submitted">Resignation submitted</option><option value="filed">State filed resignation</option><option value="mailed">Statutory notice mailed</option></select></label>{action==='submitted'?<label className="block">Resignation ground<select aria-label="Resignation ground" className="block w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)}><option value="timely-cancellation">Timely cancellation; replacement proof missing</option><option value="nonpayment">Nonpayment</option><option value="inaccurate-contact">Failure to maintain accurate contact information</option><option value="unlawful-use">Suspected unlawful use of the address</option></select></label>:null}<label className="block">Actual event date<Input aria-label="Agent event date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{(action==='replacement'||action==='cancellation'||action==='submitted')?<label className="block">Supporting record (email or filing reference and where retained)<Input aria-label={action==='submitted'?'Resignation supporting record':'Replacement proof'} value={note} onChange={e=>setNote(e.target.value)}/></label>:null}<Button type="button" size="sm" disabled={!date||save.isPending||((['replacement','cancellation'].includes(action)||(action==='submitted'&&reason!=='timely-cancellation'))&&!note.trim())} onClick={()=>save.mutate()}>Record event</Button>
 {d?.ra_resignation_submitted?<div><label>Resignation PDF<input aria-label="Resignation PDF" type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><Button type="button" size="sm" disabled={copy.isPending||(!file&&!d.ra_resignation_document)} onClick={()=>copy.mutate()}>{file?'Upload and email copy':'Retry email of existing copy'}</Button></div>:null}
 {save.isError||copy.isError?<p role="alert" className="text-destructive">{(save.error??copy.error)?.message}</p>:message?<p role="status">{message}</p>:null}</section>;
}
