/** Two real appointment -> database -> portal render paths with distinct formation dates. */
import {mkdtempSync,rmSync,mkdirSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {build} from 'esbuild';
import {chromium} from 'playwright';
import {isolateBrowser} from './browser-isolation';
const temp=mkdtempSync(join(tmpdir(),'b38-renewal-'));
Object.assign(process.env,{E2E_OFFLINE:'1',VERCEL:'',DEV_PG_DIR:join(temp,'db'),DEV_STORAGE_DIR:join(temp,'files'),DEV_MIRROR_DIR:join(temp,'mirror')});
const {app}=await import('../server/app'),{getDb}=await import('../server/db'),{newToken}=await import('../server/crypto');
const proof=await(await app.request('/api/dev/env-summary')).json();if(!proof.data?.offline||Object.values(proof.data.externals).some(Boolean))throw Error('Offline proof refused');
const db=await getDb(),cid=crypto.randomUUID(),admin=newToken(),client=newToken();
await db.query("INSERT INTO clients(id,email,name) VALUES($1,'renewal38@example.test','Renewal Test')",[cid]);
await db.query("INSERT INTO sessions(token_hash,is_admin,expires_at) VALUES($1,true,now()+interval '1 day')",[admin.tokenHash]);
await db.query("INSERT INTO sessions(token_hash,client_id,expires_at) VALUES($1,$2,now()+interval '1 day')",[client.tokenHash,cid]);
const cases=[{name:'Ordinary Appointment LLC',formed:'2026-01-15',appointed:'2026-03-20',expected:'2027-03-20',display:'March 20, 2027'},{name:'Leap Appointment LLC',formed:'2024-01-15',appointed:'2024-02-29',expected:'2025-02-28',display:'February 28, 2025'}];
const ids:string[]=[];for(const c of cases){const id=crypto.randomUUID();ids.push(id);await db.query("INSERT INTO orders(id,client_id,contact_name,contact_email,package,llc_name,payload,service_fee_cents,state_fees_cents,total_cents,status,paid_at,formed_at,square_card_id,square_customer_id,card_status) VALUES($1,$2,'Renewal Test','renewal38@example.test','NEW',$3,$4,0,0,0,'formed',now(),$5,'offline-card','offline-customer','on_file')",[id,cid,c.name,JSON.stringify({registeredAgent:{choice:'SERVICE',renewalCardConsent:true}}),c.formed]);const r=await app.request('/api/admin/orders/'+id+'/agent',{method:'POST',headers:{Cookie:'fpsllc_admin='+admin.token,'Content-Type':'application/json'},body:JSON.stringify({action:'appointment',date:c.appointed})});if(r.status!==200)throw Error('Appointment fixture refused '+await r.text());}
const root=process.env.BATCH38_UI_SOURCE||resolve(import.meta.dir,'..');
const js=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{QueryClient,QueryClientProvider}from'@tanstack/react-query';import{MemoryRouter}from'react-router-dom';import Portal from './src/pages/portal/PortalDashboard';createRoot(document.getElementById('root')).render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={[location.pathname+location.search]}><Portal/></MemoryRouter></QueryClientProvider>);`,resolveDir:root,loader:'tsx'},bundle:true,write:false,format:'esm',platform:'browser',jsx:'automatic',alias:{'@':join(root,'src')},define:{'import.meta.env':'{}','process.env.NODE_ENV':'"production"'},logLevel:'silent'});
const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(req){const u=new URL(req.url);if(u.pathname==='/app.js')return new Response(js.outputFiles[0].contents,{headers:{'Content-Type':'text/javascript'}});if(u.pathname.startsWith('/api/')){const headers=new Headers(req.headers);headers.set('Cookie','fpsllc_session='+client.token);return app.fetch(new Request(req,{headers}));}return new Response('<div id="root"></div><script type="module" src="/app.js"></script>',{headers:{'Content-Type':'text/html'}});}});
const browser=await chromium.launch();isolateBrowser(browser);const rows:{label:string;ok:boolean;detail?:unknown}[]=[];
try{const companies=(await(await app.request('/api/portal/companies',{headers:{Cookie:'fpsllc_session='+client.token}})).json()).data;const page=await browser.newPage();for(let i=0;i<cases.length;i++){const c=cases[i],company=companies.find((x:{orderId:string})=>x.orderId===ids[i]);await page.goto('http://127.0.0.1:'+server.port+'/portal?company='+ids[i]);await page.getByText('Your registered agent service is active',{exact:false}).waitFor();const text=await page.locator('body').innerText();rows.push({label:'appointment anniversary '+c.appointed,ok:company.raRenewalDate===c.expected&&text.includes('renews on '+c.display)&&!text.includes('renews on January 15'),detail:{company,display:text.match(/Your registered agent service is active[^.]+/)?.[0]}});if(process.env.BATCH38_EVIDENCE){mkdirSync(process.env.BATCH38_EVIDENCE,{recursive:true});await page.screenshot({path:join(process.env.BATCH38_EVIDENCE,'renewal-'+i+'.png'),fullPage:true});}}}finally{await browser.close();server.stop(true);rmSync(temp,{recursive:true,force:true});}
console.log('B38RENEWAL:'+JSON.stringify(rows));process.exit(rows.every(x=>x.ok)?0:1);
