import {build} from 'esbuild';import {chromium} from 'playwright';import {resolve} from 'node:path';import {mkdirSync} from 'node:fs';import {isolateBrowser} from './browser-isolation';
type Report=(label:string,ok:boolean,detail?:unknown)=>void;
export async function batch30Browser(report:Report){
 const web=resolve(import.meta.dir,'..');const entry=`import React from'react';import{createRoot}from'react-dom/client';import{flushSync}from'react-dom';import{MemoryRouter}from'react-router-dom';import{QueryClient,QueryClientProvider}from'@tanstack/react-query';import Amend from'./src/pages/portal/AmendAgreement';import{OrdersInProgress}from'./src/pages/portal/OrdersInProgress';const q=new QueryClient({defaultOptions:{queries:{retry:false}}});let root=createRoot(document.getElementById('root'));window.mount=(kind)=>{flushSync(()=>root.unmount());q.clear();root=createRoot(document.getElementById('root'));flushSync(()=>root.render(<QueryClientProvider client={q}><MemoryRouter initialEntries={['/portal/amend?company=company']} >{kind==='amend'?<Amend/>:<OrdersInProgress company='company' external={kind==='consent'?{kind:'consent',orderId:'series',nonce:1}:null} onExternalHandled={()=>{}}/>}</MemoryRouter></QueryClientProvider>));};window.ready=true;`;
 const js=await build({stdin:{contents:entry,resolveDir:web,loader:'tsx'},bundle:true,write:false,format:'iife',jsx:'automatic',platform:'browser',alias:{'@':resolve(web,'src')},define:{'import.meta.env':'{}','process.env.NODE_ENV':'"production"'},logLevel:'silent'});
 const sources=[{id:'new',company:'company',number:2,effectiveDate:'September 1, 2026',effectiveDateIso:'2026-09-01',members:[{name:'Draft Stranger'}],managers:[]},{id:'old',company:'company',number:1,effectiveDate:'January 2, 2026',effectiveDateIso:'2026-01-02',members:[{name:'Selected Owner'}],managers:[{name:'Selected Manager'}]}];
 let fail=false,sPackage=true;const sent:Record<string,unknown>[]=[];const data=(data:unknown)=>Response.json({data});
 const server=Bun.serve({hostname:'127.0.0.1',port:0,async fetch(req){const path=new URL(req.url).pathname;if(path==='/app.js')return new Response(js.outputFiles[0].text,{headers:{'content-type':'text/javascript'}});
 if(path==='/api/auth/me')return data({name:'Client Owner',email:'test@example.test'});
 if(path==='/api/portal/oa/sources')return fail?Response.json({error:{message:'Unavailable'}},{status:503}):data(sources);
 if(path==='/api/portal/oa')return data({todayEastern:'2026-09-22',seed:{llcName:'Selection LLC'},generations:sources.map(s=>({id:s.id,generation_number:s.number,effective_date:s.effectiveDate,effective_date_iso:s.effectiveDateIso}))});
 if(path==='/api/portal/services')return data({llcName:'Selection LLC',llcFormed:true,todayEastern:'2026-09-22',members:[{name:'Client Owner'}],series:[],sElection:{eligible:false,reason:sPackage?'already_ordered':'ok'},pricing:{},orders:[{id:'series',type:'series',status:'fulfilled',details:{seriesName:'Selection LLC, PS One'}},{id:'ein',type:'ein',status:'awaiting_info',details:{target:'series',seriesName:'Selection LLC, PS One'},amount_cents:5000}]});
 if(path==='/api/portal/oa/amend'||path==='/api/portal/series/consent'){sent.push({path,...await req.json()});return Response.json({error:{message:'Fixture retained request'}},{status:400});}
 if(path.startsWith('/api/'))return data([]);
 return new Response('<div id="root"></div><script src="/app.js"></script>',{headers:{'content-type':'text/html'}});}});
 const browser=await chromium.launch();const{blocked}=isolateBrowser(browser);const page=await browser.newPage({viewport:{width:1100,height:1000}});page.setDefaultTimeout(5000);
 const mount=(kind:string)=>page.evaluate(kind=>window['mount'](kind),kind);
 const scenario=async(label:string,fn:()=>Promise<boolean>)=>{try{report(label,await fn());}catch(e){report(label,false,String(e));}};
 try{await page.goto(`http://127.0.0.1:${server.port}`);await page.waitForFunction(()=>window['ready']);
 await scenario('C01-browser',async()=>{await mount('amend');const select=page.getByLabel('Operating agreement supplying the names');await select.waitFor();const noDefault=await select.inputValue()==='';await select.selectOption('old');const date=await page.getByLabel('Effective date of the operating agreement',{exact:true}).inputValue();const names=await page.getByTestId('agreement-parties').innerText();await page.getByLabel('Changes to the agreement').fill('Section 4.2 is amended.');await page.getByRole('button',{name:'Create amendment',exact:true}).click();await page.getByRole('alert').waitFor();const ok=noDefault&&date==='2026-01-02'&&names.includes('Selected Owner')&&!names.includes('Draft Stranger')&&sent.at(-1)?.generationId==='old';fail=true;try{await mount('amend');await page.getByText(/We could not load the agreements\.|We couldn't check your agreement just now\./).waitFor();const submit=page.getByRole('button',{name:'Create amendment',exact:true});const refused=await submit.count()===0||await submit.isDisabled();return ok&&refused;}finally{fail=false;}});
 await scenario('C02-browser',async()=>{await mount('consent');const select=page.getByLabel('Operating agreement supplying the names');await select.waitFor();const prepare=page.getByRole('button',{name:'Prepare the consent',exact:true});const blank=await prepare.isDisabled();await select.selectOption('old');const tick=page.getByRole('checkbox',{name:/I confirm that the members and managers shown/});const waiting=await prepare.isDisabled();await tick.check();await select.selectOption('new');const reset=!(await tick.isChecked())&&await prepare.isDisabled();await select.selectOption('old');await tick.check();await prepare.click();await page.getByText('Fixture retained request',{exact:true}).waitFor();const payload=sent.at(-1);if(process.env.BATCH30_EVIDENCE_DIR){mkdirSync(process.env.BATCH30_EVIDENCE_DIR,{recursive:true});await page.screenshot({path:resolve(process.env.BATCH30_EVIDENCE_DIR,'consent-picker.png'),fullPage:true});}return blank&&waiting&&reset&&payload?.generationId==='old'&&payload?.partiesConfirmed===true;});
 await scenario('C03',async()=>{const texts:string[]=[];for(const paid of [true,false]){sPackage=paid;await mount('ein');await page.getByRole('button',{name:/Provide.*details/i}).click();const dialog=page.getByRole('dialog');await dialog.waitFor();texts.push(await dialog.innerText());}return blocked.size===0&&texts.every(t=>t.includes('We will apply for this protected series’ EIN as a disregarded entity.')&&!t.includes('We will report it as an S corporation'));});
 }finally{await browser.close();server.stop(true);}
}
