import { chromium, type Browser } from 'playwright';
import { mkdirSync,readFileSync,mkdtempSync,rmSync } from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {isolateBrowser,guardedRoute} from './browser-isolation';import {startIsolatedStack} from './isolated-stack';
import {agentFixture} from '../server/batch06-check';import {orderFormSchema} from '../server/validation';import {buildPayload} from '../src/components/forms/florida-llc/buildPayload';import {validateStep} from '../src/components/forms/florida-llc/stepValidation';import * as v from '../src/components/forms/florida-llc/validation';import {formatDate} from '../src/lib/datetime';import {filingGroups} from '../server/filing';import {STEPS,type StepKey} from '../src/components/forms/florida-llc/steps';
type Check=(ok:boolean,label:string,detail?:unknown)=>void;
async function shot(page:import('playwright').Page,name:string){if(process.env.SHOT_DIR){mkdirSync(process.env.SHOT_DIR,{recursive:true});await page.screenshot({path:process.env.SHOT_DIR+'/'+name+'.png',fullPage:true,animations:'disabled'});}}
async function routes(){
 const {app}=await import('../server/app'),{getDb}=await import('../server/db'),{newToken}=await import('../server/crypto');
 const env=await (await app.request('/api/dev/env-summary')).json();if(!env.data?.offline||Object.values(env.data.externals).some(Boolean))throw Error('Not isolated');
 const db=await getDb(),client=crypto.randomUUID(),id=crypto.randomUUID(),token=newToken(),admin=newToken();
 await db.query("INSERT INTO clients(id,email,name) VALUES($1,$2,'Ten Client')",[client,`ten-${client}@example.test`]);
 await db.query("INSERT INTO sessions(token_hash,client_id,is_admin,expires_at) VALUES($1,$2,false,now()+interval '1 day')",[token.tokenHash,client]);
 await db.query("INSERT INTO sessions(token_hash,is_admin,expires_at) VALUES($1,true,now()+interval '1 day')",[admin.tokenHash]);
 const fixture=agentFixture({effectiveDateOption:'SPECIFIC',requestedEffectiveDate:'2020-01-01'});
 await db.query("INSERT INTO orders(id,client_id,contact_name,contact_email,package,llc_name,payload,service_fee_cents,state_fees_cents,total_cents,status,paid_at,formed_at) VALUES($1,$2,'Ten Client','ten@example.test','formation','Batch Ten LLC',$3,0,0,0,'formed',now(),now())",[id,client,JSON.stringify(buildPayload(fixture))]);
 const req=async(path:string,body?:unknown,isAdmin=false)=>{const res=await app.request('/api'+path,{method:body===undefined?'GET':'POST',headers:{Cookie:`${isAdmin?'fpsllc_admin':'fpsllc_session'}=${isAdmin?admin.token:token.token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return {status:res.status,body:await res.json()};};
 const errors:Awaited<ReturnType<typeof req>>[]=[];for(const body of [{suffix:''},{suffix:'x'.repeat(61)},{suffix:'PS Ten',purpose:'x'.repeat(301)}])errors.push(await req(`/portal/services/series?company=${id}`,body));
 const seed=await req(`/portal/oa?company=${id}`),office=await req(`/admin/orders/${id}`,undefined,true),order=await req('/orders',fixture),invalid=await req('/orders',{...fixture,requestedEffectiveDate:'2026-02-30'});
 console.log('B10:'+JSON.stringify({errors,seedDate:seed.body.data?.todayEastern,office:office.body.data?.groups,order,invalid}));
}
export async function batch10Walk(browser:Browser,web:string,check:Check){
 const attempt=async(label:string,fn:()=>Promise<void>)=>{try{await fn();}catch(e){check(false,label,String(e));}};
 const open=async(key:StepKey,data=agentFixture())=>{const p=await browser.newPage();p.setDefaultTimeout(4500);await p.addInitScript(({data,step})=>localStorage.setItem('fl-llc-formation-draft-v1',JSON.stringify({__draft:2,data,stepIndex:step,maxStep:18,visited:Array.from({length:19},(_,i)=>i)})),{data,step:STEPS.findIndex(s=>s.key===key)});await p.goto(web+'/form-llc');await p.locator('main h2').waitFor();return p;};
 const dir=mkdtempSync(join(tmpdir(),'batch10-routes-'));let rt:{errors:{status:number;body:{error?:{message:string}}}[];seedDate?:string;office:unknown;order:{status:number};invalid:{status:number}};
 try{const child=Bun.spawn(['bun',import.meta.filename,'--routes'],{cwd:process.cwd(),env:{...process.env,E2E_OFFLINE:'1',VERCEL:'',DEV_PG_DIR:dir},stdout:'pipe',stderr:'pipe'});const [out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);const line=out.split('\n').find(x=>x.startsWith('B10:'));if(code||!line)throw Error(`Route fixture failed ${code}: ${err}\n${out.slice(-1000)}`);rt=JSON.parse(line.slice(4));}finally{rmSync(dir,{recursive:true,force:true});}
 const comment=readFileSync(new URL('../server/sunbiz.ts',import.meta.url),'utf8').split('const HOLD_DAYS')[0].slice(-950);check(comment.includes('605.0717(2)')&&comment.includes('proxy')&&comment.includes('120'),'batch10 44: name-hold comment cites both rules',comment);
 await attempt('batch10 61: one business day estimate and automatic nearest permitted filing date',async()=>{const d=agentFixture({effectiveDateOption:'SPECIFIC',requestedEffectiveDate:'2020-01-01'}),p=await open('effective',d);try{const t=await p.locator('main').innerText(),date=filingGroups(buildPayload(d),'2026-09-16').flatMap(g=>g.fields).find(f=>f.key==='effectiveDate')?.value;const accepted=orderFormSchema.safeParse(d).success&&!validateStep('effective',d).requestedEffectiveDate;check(accepted&&date==='2026-09-09'&&t.includes('within one business day')&&t.includes('cannot guarantee an exact effective date')&&rt.order.status===200&&rt.invalid.status===400,'batch10 61: one business day estimate and automatic nearest permitted filing date',{date,accepted,t,route:rt.order,office:rt.office});if(process.env.SHOT_DIR){mkdirSync(process.env.SHOT_DIR,{recursive:true});await p.screenshot({path:process.env.SHOT_DIR+'/effective-date.png',fullPage:true});}}finally{await p.close();}});
 await attempt('batch10 78: missing designator asks for selection',async()=>{const p=await open('name',agentFixture({llcDesignator:''}));try{const t=await p.locator('main').innerText();check(t.includes('Choose a designator above to complete the name.')&&!t.includes('Florida LLC name must include'),'batch10 78: missing designator asks for selection',t);}finally{await p.close();}});
 await attempt('batch10 84: review shows the selected calendar day in words',async()=>{const p=await open('review',agentFixture({effectiveDateOption:'SPECIFIC',requestedEffectiveDate:'2026-10-01'}));try{const t=await p.getByRole('heading',{name:'Effective Date',exact:true}).locator('../..').innerText();check(t.includes('October 1, 2026')&&!t.includes('2026-10-01'),'batch10 84: review shows the selected calendar day in words',t);}finally{await p.close();}});
 const named=['PS-4','PS 4','P.S. 4','Protected Series-4'].map(n=>({name:n,valid:v.hasProtectedSeriesPhrase(n),key:v.seriesDedupeKey(n)})),dup=orderFormSchema.safeParse(agentFixture({series:[{id:'a',name:'PS-4'},{id:'b',name:'PS 4'}]}));check(named.every(x=>x.valid&&x.key==='4')&&!dup.success&&dup.error.issues.some(i=>/duplicate|same|distinct|unique/i.test(i.message)),'batch10 91: series separators validate and deduplicate consistently',{named,issues:dup.success?[]:dup.error.issues});
 const ordinary=['Millcreek Holdings','Hillcrest Rentals','Wellcome Farms','Fullcircle Properties'].map(n=>({name:n,designator:v.nameContainsLegalDesignator(n),accepted:orderFormSchema.safeParse(agentFixture({exactNameOnly:false,alternateName1:n})).success}));check(ordinary.every(x=>!x.designator&&x.accepted),'batch10 92: embedded llc letters are not designators',ordinary);
 const mismatches=[agentFixture({desiredLlcName:'Acme PLLC'}),agentFixture({formationType:'PLLC',llcDesignator:'PLLC',purposeType:'PROFESSIONAL',businessPurposeText:'Medicine',desiredLlcName:'Acme LLC'})].map(d=>{const x=orderFormSchema.safeParse(d);return {client:validateStep('name',d).desiredLlcName,server:x.success?[]:x.error.issues.filter(i=>i.path[0]==='desiredLlcName')};});check(mismatches.every(x=>!!x.client&&x.server.length>0),'batch10 93: typed name ending agrees with company type',mismatches);
 const context=await browser.newContext({timezoneId:'Asia/Tokyo'}),p=await context.newPage();p.setDefaultTimeout(4500);let savedDate:string|undefined;let freshDate='2026-09-09',failRefresh=false;
 await p.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(value:string)=>{(window as unknown as {copiedText:string}).copiedText=value;}}});});
 const services={llcName:'Ten Company LLC',dev:true,llcFormed:true,members:[],series:[],orders:[{id:'s10',type:'series',status:'fulfilled',details:{seriesName:'Ten Company LLC - PS 4'},created_at:'2026-09-19T01:00:00Z',documentId:'doc10'}],sElection:{eligible:true,reason:'ok',orderBy:'2026-09-20T01:00:00Z'},todayEastern:'2026-09-19',einCompanyOrdered:false,pricing:{seriesCents:5000,einCents:5000,sElectionCents:5000,certStatusCents:1500,certifiedCopyCents:4000}};
 await guardedRoute(p,'**/api/**',async route=>{const path=new URL(route.request().url()).pathname,send=(data:unknown)=>route.fulfill({contentType:'application/json',body:JSON.stringify({data})});
 if(path==='/api/auth/me')return send({name:'Ten Owner',email:'ten@example.test'});
 if(path==='/api/portal/companies')return send([{orderId:'co10',llcName:'Ten Company LLC',formed:true,registeredAgentChoice:'SELF'}]);
 if(path==='/api/portal/documents')return send([{id:'doc10',kind:'psd',title:'Protected Series Designation',seriesNames:['Ten Company LLC - PS 4'],created_at:'2026-09-19T12:00:00Z',size_bytes:20}]);
 if(path==='/api/portal/services')return send(services);
 if(path==='/api/portal/oa')return send({todayEastern:'2026-09-19',version:'single',multiOwner:false,memberManaged:false,rev:0,seed:{llcName:'Ten Company LLC',filingPath:'NEW',members:[{name:'Ten Owner',address:'1 Main St'}],series:[],principalAddress:'1 Main St',managerNames:[],managerEntities:[],managementStructure:'MANAGER_MANAGED'},answers:savedDate?{effectiveDate:savedDate}:{},generations:[{id:'g10',effective_date_iso:'2026-01-01',effective_date:'January 1, 2026',created_at:'2026-01-01T12:00:00Z',generation_number:1}]});
 if(path==='/api/portal/oa/answers')return send({ok:true,rev:1});
 if(path==='/api/admin/me')return send({ok:true});
 if(path==='/api/admin/orders')return send({orders:[{id:'co10',client_id:'c10',llc_name:'Ten Company LLC',contact_name:'Ten Owner',contact_email:'ten@example.test',status:'formed',created_at:'2025-09-18T12:00:00Z',formed_at:'2025-09-18T12:00:00Z',paid_at:'2025-09-18T12:00:00Z',total_cents:0,series_count:1}],total:1,shown:1});
 if(path==='/api/admin/services')return send([{id:'cert10',type:'certificate-of-status',status:'in_progress',llc_name:'Ten Company LLC',client_name:'Ten Owner',client_email:'ten@example.test',client_id:'c10',formation_order_id:'co10',created_at:'2025-09-20T01:00:00Z',paid_at:'2025-09-20T01:00:00Z',amount_cents:1500,details:{},has_secret:false,ein_pending:false}]);
 if(path==='/api/admin/orders/co10'){if(failRefresh)return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Fixture unavailable'}})});return send({id:'co10',llcName:'Ten Company LLC',status:'paid',filingPath:'NEW',contactName:'Ten Owner',contactEmail:'ten@example.test',createdAt:'2026-09-19T12:00:00Z',groups:[{title:'Filing date',fields:[{key:'effectiveDate',label:'Effective date',value:freshDate}]}],copiedFields:{},series:[],documents:[],services:[]});}
 if(path==='/api/admin/orders/co10/copied')return send({ok:true});
 if(path==='/api/admin/services/cert10')return send({details:{}});
 return send([]);});
 await attempt('batch10 128:florida-date: document defaults use server Eastern date',async()=>{await p.goto(web+'/portal/agreement?company=co10');await p.getByRole('button',{name:'Continue',exact:true}).click();await p.getByLabel('Effective date',{exact:true}).waitFor();const oa=await p.getByLabel('Effective date',{exact:true}).inputValue();await shot(p,'agreement-default');savedDate='2026-08-03';await p.reload();await p.getByRole('button',{name:'Continue',exact:true}).click();await p.getByLabel('Effective date',{exact:true}).waitFor();const saved=await p.getByLabel('Effective date',{exact:true}).inputValue();await p.goto(web+'/portal/amend?company=co10');const box=p.locator('input[type=date]').last();await box.waitFor();const amend=await box.inputValue();await shot(p,'amendment-default');await p.goto(web+'/portal?company=co10');await p.waitForLoadState('networkidle');await p.getByRole('button',{name:/consent/i}).first().click();const c=p.getByRole('dialog').locator('input[name=effectiveDate]');await c.waitFor();const consent=await c.inputValue();await shot(p,'consent-default');check(oa==='2026-09-19'&&saved==='2026-08-03'&&amend==='2026-09-19'&&consent==='2026-09-19'&&/^\d{4}-\d{2}-\d{2}$/.test(rt.seedDate??''),'batch10 128:florida-date: document defaults use server Eastern date',{oa,saved,amend,consent,server:rt.seedDate});});
 await attempt('batch10 128:viewer-zone-display: service deadlines use Eastern display',async()=>{await p.goto(web+'/portal?company=co10');await p.waitForLoadState('networkidle');const t=await p.locator('main').innerText();check(t.includes('September 19, 2026')&&!t.includes('September 20, 2026')&&formatDate('2026-10-01')==='October 1, 2026','batch10 128:viewer-zone-display: service deadlines use Eastern display',t);});
 await attempt('batch10 186: office dates include year and Eastern day',async()=>{await p.goto(web+'/admin');await p.getByRole('button',{name:/Cert[.] of Status.*in progress/i}).first().click();const d=p.getByRole('dialog');await d.waitFor();const t=await d.innerText();await shot(p,'office-service-date');check(t.includes('September 19, 2025'),'batch10 186: office dates include year and Eastern day',t);});
 await attempt('batch10 supplemental: office copy refreshes date and refuses a failed refresh',async()=>{await p.goto(web+'/admin');await p.getByRole('button',{name:/Ten Company LLC.*Ten Owner/}).click();await p.getByRole('button',{name:'Copy Effective date',exact:true}).waitFor();freshDate='2026-09-10';await p.getByRole('button',{name:'Copy Effective date',exact:true}).click();await p.waitForFunction(()=>!!(window as unknown as {copiedText:string}).copiedText);const copied=await p.evaluate(()=>(window as unknown as {copiedText:string}).copiedText);if(copied!=='2026-09-10'){check(false,'batch10 supplemental: office copy refreshes date and refuses a failed refresh',{copied});return;}await p.waitForLoadState('networkidle');failRefresh=true;await p.getByRole('button',{name:'Copy Effective date',exact:true}).click();await p.getByTestId('copy-failed').waitFor({timeout:15000});const after=await p.evaluate(()=>(window as unknown as {copiedText:string}).copiedText);check(copied==='2026-09-10'&&after===copied,'batch10 supplemental: office copy refreshes date and refuses a failed refresh',{copied,after});});await context.close();
 const prior=process.env.TZ,dates:{zone:string;early:string|null;late:string|null}[]=[];try{for(const zone of ['America/New_York','America/Los_Angeles','Asia/Tokyo','UTC']){process.env.TZ=zone;dates.push({zone,early:v.validateEffectiveDate('2026-09-09',new Date('2026-09-16T16:00:00Z')),late:v.validateEffectiveDate('2026-12-16',new Date('2026-09-16T16:00:00Z'))});}}finally{if(prior===undefined)delete process.env.TZ;else process.env.TZ=prior;}check(dates.every(x=>x.early===null&&x.late!==null),'batch10 N4.02: effective date endpoints do not shift with timezone',dates);
 const holidays=['2026-09-07','2026-11-26','2027-07-05'].map(d=>({day:d,business:v.isBusinessDay(new Date(d+'T16:00:00Z'))}));check(holidays.every(x=>!x.business)&&v.isBusinessDay(new Date('2026-07-03T16:00:00Z')),'batch10 N4.03: business days exclude banking holidays',holidays);
 const expected=['Enter a series identifier.','The series identifier can be at most 60 characters.','The purpose can be at most 300 characters.'];check(rt.errors.every((x,i)=>x.status===400&&x.body.error?.message===expected[i]),'batch10 159: series errors identify the invalid field',rt.errors);
}
if(import.meta.main){if(process.argv.includes('--routes')){await routes();process.exit(0);}const s=await startIsolatedStack({cwd:process.cwd()}),b=await chromium.launch({headless:true});await isolateBrowser(b);let failed=0;try{await batch10Walk(b,s.web,(ok,label,detail)=>{console.log(JSON.stringify({ok,label,detail:ok?undefined:detail}));if(!ok)failed++;});}finally{await b.close();s.stop();}process.exit(failed?1:0);}
