/**
 * Pulls the documents that are STILL authored in Word out of Dropbox and into
 * the repo, and refreshes their markdown mirrors.
 *
 * It deliberately does NOT touch anything that is now a master. The masters —
 * the five operating agreements and the Owner's Manual — live in this repo as
 * markdown, and their Word files are OUTPUT, regenerated by
 * .claude/hooks/update-word-docs.sh. Pulling those back from Dropbox would
 * overwrite the master with a generated file.
 *
 *   bun run docs:sync
 */
import { copyFile, mkdir, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCE_DIR = join(HERE, "source");

const ORIGIN =
  "/Users/adam/Library/CloudStorage/Dropbox/00 SharedWithMac/FPSLLC Operating Agreement";

/** Still authored in Word. Pulled in and mirrored to markdown. */
const WORD_AUTHORED: { file: string; md?: string }[] = [
  { file: "Series LLC Owners Manual.pdf" }, // superseded PDF, kept for history
];

/** Generated FROM a repo master. Never pulled back — that would overwrite the
 *  master with its own output. */
const GENERATED = new Set([
  "Series LLC Owners Manual - REVISED DRAFT.docx",
  "FPSLLC Operating Agreement - Manager-Managed Single Member (Disregarded) - DRAFT.docx",
  "FPSLLC Operating Agreement - Manager-Managed Multi-Member (Partnership) - DRAFT.docx",
  "FPSLLC Operating Agreement - Manager-Managed (S Corporation) - DRAFT.docx",
  "FPSLLC Operating Agreement - Member-Managed Multi-Member (Partnership) - DRAFT.docx",
  "FPSLLC Operating Agreement - Member-Managed (S Corporation) - DRAFT.docx",
  "FPSLLC Operating Agreement Instructions - DRAFT.docx",
  "FPSLLC Redline - Manager-Managed Partnership vs S Corporation.docx",
  "FPSLLC Redline - Manager-Managed vs Member-Managed Partnership.docx",
  "FPSLLC Redline - Manager-Managed vs Member-Managed S Corporation.docx",
  "FPSLLC Redline - Member-Managed Partnership vs S Corporation.docx",
]);

/** Research material deliberately not committed: samples and other people's
 *  documents. Listed so the unlisted-file check stays meaningful. */
const REFERENCE_ONLY = new Set([
  "Florida Operating Agreement.pdf",
  "SM1003-001.Smith.DE LLC Operating Agreement.p'ship.pdf",
  // a client's document — reference only, never ours to redistribute
  "Operating Agreement- pilfered from client.pdf",
]);

await mkdir(SOURCE_DIR, { recursive: true });

let copied = 0;
const missing: string[] = [];
for (const doc of WORD_AUTHORED) {
  const from = join(ORIGIN, doc.file);
  if (!existsSync(from)) {
    missing.push(doc.file);
    continue;
  }
  await copyFile(from, join(SOURCE_DIR, doc.file));
  copied++;
  if (doc.md) {
    const res = spawnSync(
      "python3",
      [join(HERE, "docx-to-md.py"), join(SOURCE_DIR, doc.file), join(HERE, doc.md)],
      { encoding: "utf8" },
    );
    if (res.status !== 0) {
      console.error(`  convert failed: ${doc.file}\n${res.stderr}`);
      process.exitCode = 1;
    }
  }
}

// Anything in the origin folder this script does not recognise is a deliverable
// with no home here — surface it rather than let it sit outside version control.
const known = new Set([
  ...WORD_AUTHORED.map((d) => d.file),
  ...GENERATED,
  ...REFERENCE_ONLY,
]);
const unlisted: string[] = [];
try {
  for (const name of await readdir(ORIGIN)) {
    if (name.startsWith(".") || !/\.(docx|pdf)$/i.test(name)) continue;
    if (!known.has(name)) unlisted.push(name);
  }
} catch {
  // origin unreachable (different machine) — the committed copies still stand
}

console.log(`pulled ${copied}/${WORD_AUTHORED.length} Word-authored documents`);
console.log(`${GENERATED.size} generated documents left alone (run .claude/hooks/update-word-docs.sh)`);
if (missing.length) {
  console.error("MISSING from the origin folder — check Dropbox:");
  for (const m of missing) console.error("  " + m);
  process.exitCode = 1;
}
if (unlisted.length) {
  console.error("NOT TRACKED — in the origin folder but not in docs/README.md:");
  for (const u of unlisted) console.error("  " + u);
  process.exitCode = 1;
}
