import { defaultFormData } from '../src/components/forms/florida-llc/defaults';
import { buildPayload } from '../src/components/forms/florida-llc/buildPayload';
import { validateStep } from '../src/components/forms/florida-llc/stepValidation';
import { orderFormSchema } from './validation';
import { summaryMarkdown, type SummaryOrderRow } from './order-summary';
import type { FloridaLLCFormData } from '../src/components/forms/florida-llc/types';
export function agentFixture(extra: Partial<FloridaLLCFormData> = {}): FloridaLLCFormData {
 const a={address1:'101 Main St',city:'Orlando',state:'FL',zip:'32803',country:'United States'};
 return {...structuredClone(defaultFormData),filingPath:'NEW',isFloridaDomesticEntityOnly:true,notLegalAdvice:true,publicRecordNotice:true,clientFirstName:'Jane',clientLastName:'Owner',clientEmail:'batch06@example.test',confirmClientEmail:'batch06@example.test',clientAddress:a,desiredLlcName:'Batch Six',llcDesignator:'LLC',exactNameOnly:true,nameSearchAcknowledgment:true,governmentAffiliationAcknowledgment:true,lawfulPurposeNameAcknowledgment:true,principalAddress:a,mailingAddress:a,registeredAgentChoice:'SELF',registeredAgentType:'INDIVIDUAL',registeredAgentFirstName:'John',registeredAgentLastName:'Smith',registeredAgentSuffix:'Jr.',registeredAgentStreetAddress1:a.address1,registeredAgentCity:a.city,registeredAgentState:'FL',registeredAgentZip:a.zip,registeredAgentNotSameAsLlc:true,registeredAgentPhysicalAddressAcknowledgment:true,registeredAgentAcceptanceName:'John Smith, Jr.',registeredAgentAcceptanceCapacity:'INDIVIDUAL_AGENT',registeredAgentElectronicSignature:'John Smith, Jr.',registeredAgentAcceptanceCheckbox:true,registeredAgentSignatureAuthorizationCheckbox:true,managementStructure:'MANAGER_MANAGED',managers:[{id:'m6',role:'MGR',personOrEntity:'INDIVIDUAL',firstName:'Jane',lastName:'Owner',streetAddress1:a.address1,city:a.city,state:'FL',zip:a.zip,country:a.country}],members:[],purposeType:'GENERAL',correspondentName:'Jane Owner',correspondentEmail:'batch06@example.test',confirmCorrespondentEmail:'batch06@example.test',series:[{id:'s1',name:'PS One'}],seriesOwnershipAcknowledgment:true,articlesSignerChoice:'SERVICE',articlesSignerAppointment:true,atLeastOneMemberAcknowledgment:true,accuracyAcknowledgment:true,addressAccuracyAcknowledgment:true,termsOfServiceAcknowledgment:true,publicRecordAcknowledgment:true,legalAdviceAcknowledgment:true,...{registeredAgentResidencyAcknowledgment:true,registeredAgentExistingRecordAcknowledgment:true,registeredAgentSeriesAgreementAcknowledgment:true},...extra};
}
export function summaryFor(data:FloridaLLCFormData):string{return summaryMarkdown({id:'batch06',llc_name:'Batch Six LLC',package:data.filingPath,payload:buildPayload(data),contact_name:'Jane Owner',contact_email:data.clientEmail,line_items:[],service_fee_cents:0,state_fees_cents:0,total_cents:0,status:'pending_payment',created_at:'2026-09-19T12:00:00Z',paid_at:null,square_order_id:null,square_payment_id:null,submitted_ip:null,submitted_user_agent:null}as SummaryOrderRow);}
export function batch06Checks(check:(ok:boolean,label:string,detail?:unknown)=>void){
 const valid=agentFixture(),parse=(x:FloridaLLCFormData)=>orderFormSchema.safeParse(x);check(parse(valid).success,'batch06 complete personal-agent order passes',parse(valid));
 for(const field of ['registeredAgentAcceptanceName','registeredAgentElectronicSignature']as const){const bad={...valid,[field]:'Different Person'},p=parse(bad),e=validateStep('acceptance',bad);check(!p.success&&!!e[field],`batch06 server and browser refuse mismatched ${field}`,{parsed:p,errors:e});}
 check(parse({...valid,registeredAgentElectronicSignature:' John Smith, Jr. '}).success,'batch06 outer whitespace remains allowed');
 const entity=agentFixture({filingPath:'CONVERT',existingLlcName:'Batch Six LLC',sunbizDocumentNumber:'L26000000001',conversionAuthorityAcknowledgment:true,registeredAgentType:'ENTITY',registeredAgentBusinessEntityName:'Existing Agent Inc.',registeredAgentFirstName:'',registeredAgentLastName:'',registeredAgentSuffix:'',registeredAgentNotSameAsLlc:false,registeredAgentPhysicalAddressAcknowledgment:false,registeredAgentAcceptanceName:'',registeredAgentElectronicSignature:'',registeredAgentAcceptanceCheckbox:false,registeredAgentSignatureAuthorizationCheckbox:false});
 check(parse(entity).success&&Object.keys(validateStep('agent',entity)).length===0,'batch06 retained entity agent passes without a personal acceptance',{parsed:parse(entity),errors:validateStep('agent',entity)});
 for(const field of ['registeredAgentSeriesAgreementAcknowledgment','registeredAgentExistingRecordAcknowledgment']as const){const p=parse({...entity,[field]:false});check(!p.success,`batch06 server requires ${field}`,p);}
 const nr={...valid,registeredAgentResidencyAcknowledgment:false};check(!parse(nr).success&&Object.keys(validateStep('agent',nr)).length>0,'batch06 residency is required by server and browser',parse(nr));
 const sm=summaryFor(entity);check(sm.includes('registered agent has agreed to serve')&&!sm.includes('I am accepting this role personally')&&!sm.includes('### Agent acceptance'),'batch06 retained-agent summary records actual consent only',sm);
 check(!parse({...valid,registeredAgentType:'ENTITY',registeredAgentBusinessEntityName:'Third Party'}).success,'batch06 new formation cannot bypass the supported agent choices');check(!parse({...valid,registeredAgentStreetAddress1:'P.O. Box 7'}).success,'batch06 server refuses agent PO box');
 const svc=agentFixture({registeredAgentChoice:'SERVICE',raRenewalCardConsent:true});check(parse(svc).success,'batch06 service agent still passes',parse(svc));
 const sms=summaryFor({...svc,filingPath:'CONVERT',existingLlcName:'Batch Six LLC',conversionAuthorityAcknowledgment:true});check(sms.includes('and the change of registered agent with the Florida Division'),'batch06 office summary includes authorized agent change',sms);
}
if(import.meta.main){let failed=0;batch06Checks((ok,label,detail)=>{console.log(JSON.stringify({ok,label,detail:ok?undefined:detail}));if(!ok)failed++;});process.exit(failed?1:0);}
