import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
export async function batch04Checks(check:(label:string,ok:boolean,detail?:unknown)=>void){
 const dir=mkdtempSync(join(tmpdir(),'batch04-'));
 try{const child=Bun.spawn(['bun',import.meta.filename,'--child'],{cwd:process.cwd(),env:{...process.env,E2E_OFFLINE:'1',VERCEL:'',DEV_PG_DIR:join(dir,'db'),DEV_STORAGE_DIR:join(dir,'storage'),ADMIN_PASSWORD:'dev-admin'},stdout:'pipe',stderr:'pipe'});
 const [out,err,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);
 const rows=out.split('\n').filter(s=>s.startsWith('BATCH04:')).map(s=>JSON.parse(s.slice(8)));for(const r of rows)check(r.label,r.ok,r.detail);
 if(code||rows.length<7)throw new Error(`Fixture failed ${code}: ${err}\n${out}`);
 }finally{rmSync(dir,{recursive:true,force:true});}
}
async function child(){
 const {app}=await import('./app'),{getDb}=await import('./db'),{newToken,hashPassword}=await import('./crypto'),{env}=await import('./env'),email=await import('./email');
 const db=await getDb();const check=(label:string,ok:boolean,detail?:unknown)=>console.log('BATCH04:'+JSON.stringify({label,ok,detail:ok?undefined:detail}));
 let mailFails=false,mailCount=0,ip=0;env.RESEND_API_KEY='synthetic-not-real';const originalFetch=globalThis.fetch;
 globalThis.fetch=(async(input:RequestInfo|URL)=>{if(String(input)!=='https://api.resend.com/emails')throw new Error('External request refused');mailCount++;return new Response(JSON.stringify(mailFails?{error:'synthetic outage'}:{id:'fixture'}),{status:mailFails?503:200,headers:{'Content-Type':'application/json'}});}) as typeof fetch;
 const client=crypto.randomUUID(),order=crypto.randomUUID(),session=newToken();
 await db.query("INSERT INTO clients(id,email,name) VALUES($1,'batch04@example.test','Batch Four')",[client]);
 await db.query("INSERT INTO sessions(token_hash,client_id,expires_at) VALUES($1,$2,now()+interval '1 day')",[session.tokenHash,client]);
 const req=(path:string,body?:unknown,cookie=session.token)=>app.request('/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','x-forwarded-for':`192.0.2.${++ip}`,Cookie:`fpsllc_session=${cookie}`},body:body===undefined?undefined:JSON.stringify(body)});
 await db.query("INSERT INTO orders(id,client_id,contact_name,contact_email,package,llc_name,payload,service_fee_cents,state_fees_cents,total_cents,status,paid_at) VALUES($1,$2,'Batch Four','batch04@example.test','NEW','Batch Four LLC',$3,0,0,0,'paid',now())",[order,client,JSON.stringify({filingPath:'NEW',series:{seriesList:[{seriesName:'PS 1'}]}})]);
 const resend: {status:string;http:number;sent:boolean}[]=[];for(const status of ['paid','filed','formed']){await db.query('UPDATE orders SET status=$1 WHERE id=$2',[status,order]);const r=await req(`/orders/${order}/resend-welcome`,{});resend.push({status,http:r.status,...(await r.json()).data});}
 check('batch04 64: welcome resend follows paid account state',resend.every(r=>r.http===200&&r.sent===true),resend);
 await db.query("UPDATE orders SET status='paid' WHERE id=$1",[order]);mailFails=true;const failed=await req(`/orders/${order}/resend-welcome`,{});const failedBody=await failed.json();mailFails=false;const retry=await req(`/orders/${order}/resend-welcome`,{});
 check('batch04 N4.06: failed welcome email remains retryable',failed.status===503&&failedBody.error?.code==='EMAIL_FAILED'&&retry.status===200&&(await retry.json()).data?.sent===true,{status:failed.status,failedBody});
 const before=mailCount;await db.query('UPDATE orders SET paid_at=NULL WHERE id=$1',[order]);const unpaid=await req(`/orders/${order}/resend-welcome`,{}),unknown=await req(`/orders/${crypto.randomUUID()}/resend-welcome`,{});
 await db.query('UPDATE clients SET password_hash=$1 WHERE id=$2',[await hashPassword('Old-password-123'),client]);await db.query('UPDATE orders SET paid_at=now() WHERE id=$1',[order]);const ready=await req(`/orders/${order}/resend-welcome`,{});
 check('batch04 resend refuses unpaid unknown and password-ready accounts without sending',mailCount===before&&[await unpaid.json(),await unknown.json(),await ready.json()].every(x=>x.data?.sent===false));
 const malformed=await req('/auth/login',{email:'adam@',password:'typed'});const malformedBody=await malformed.json();check('batch04 160: malformed login explains valid input',malformed.status===400&&malformedBody.error?.message==='Enter a valid email address and your password.',malformedBody);
 const unrelated=crypto.randomUUID(),unrelatedToken=newToken();await db.query("INSERT INTO clients(id,email,name,pending_email) VALUES($1,'unrelated@example.test','Unrelated Client','keep@example.test')",[unrelated]);await db.query("INSERT INTO auth_tokens(token_hash,client_id,purpose,payload,expires_at) VALUES($1,$2,'verify_email','keep@example.test',now()+interval '1 hour')",[unrelatedToken.tokenHash,unrelated]);
 const deniedToken=newToken();await db.query("UPDATE clients SET pending_email='pending@example.test' WHERE id=$1",[client]);await db.query("INSERT INTO auth_tokens(token_hash,client_id,purpose,payload,expires_at) VALUES($1,$2,'verify_email','pending@example.test',now()+interval '1 hour')",[deniedToken.tokenHash,client]);const deniedChange=await req('/portal/account/password',{currentPassword:'Wrong-password-123',newPassword:'New-password-123'});const [deniedState]=await db.query<{pending_email:string}>('SELECT pending_email FROM clients WHERE id=$1',[client]);check('batch04 wrong password cannot cancel an email change',deniedChange.status===401&&deniedState.pending_email==='pending@example.test');
 const authCases: {mode:string;status:number;pending:string|null;used:boolean;verify:number;email:string;sessions:number;keptCurrent:boolean}[]=[];
 for(const mode of ['change','reset']){
 const t=newToken(),verify=newToken(),other=newToken();await db.query('UPDATE clients SET password_hash=$1,pending_email=$2 WHERE id=$3',[await hashPassword('Old-password-123'),'attacker@example.test',client]);
 await db.query("INSERT INTO sessions(token_hash,client_id,expires_at) VALUES($1,$2,now()+interval '1 day'),($3,$2,now()+interval '1 day')",[t.tokenHash,client,other.tokenHash]);
 await db.query("INSERT INTO auth_tokens(token_hash,client_id,purpose,payload,expires_at) VALUES($1,$2,'verify_email','attacker@example.test',now()+interval '1 hour')",[verify.tokenHash,client]);
 let r:Response;if(mode==='change')r=await req('/portal/account/password',{currentPassword:'Old-password-123',newPassword:'New-password-123'},t.token);else{const reset=newToken();await db.query("INSERT INTO auth_tokens(token_hash,client_id,purpose,expires_at) VALUES($1,$2,'reset_password',now()+interval '1 hour')",[reset.tokenHash,client]);r=await req('/auth/set-password',{token:reset.token,password:'New-password-123'},t.token);}
 const [state]=await db.query<{pending_email:string|null}>('SELECT pending_email FROM clients WHERE id=$1',[client]);const [tok]=await db.query<{used_at:unknown}>('SELECT used_at FROM auth_tokens WHERE token_hash=$1',[verify.tokenHash]);const confirm=await req('/auth/verify-email',{token:verify.token});const [after]=await db.query<{email:string}>('SELECT email FROM clients WHERE id=$1',[client]);const sessions=await db.query<{token_hash:string}>('SELECT token_hash FROM sessions WHERE client_id=$1',[client]);
 authCases.push({mode,status:r.status,pending:state.pending_email,used:!!tok.used_at,verify:confirm.status,email:after.email,sessions:sessions.length,keptCurrent:sessions.some(s=>s.token_hash===t.tokenHash)});await db.query("UPDATE clients SET email='batch04@example.test' WHERE id=$1",[client]);}
 check('batch04 200: password changes cancel pending email changes',authCases.every(x=>x.status===200&&x.pending===null&&x.used&&x.verify===400&&x.email==='batch04@example.test'&&x.sessions===1&&x.keptCurrent===(x.mode==='change')),authCases);
 const raceSession=newToken(),raceToken=newToken();await db.query("INSERT INTO sessions(token_hash,client_id,expires_at) VALUES($1,$2,now()+interval '1 day')",[raceSession.tokenHash,client]);await db.query('UPDATE clients SET pending_email=$1 WHERE id=$2',['race@example.test',client]);await db.query("INSERT INTO auth_tokens(token_hash,client_id,purpose,payload,expires_at) VALUES($1,$2,'verify_email','race@example.test',now()+interval '1 hour')",[raceToken.tokenHash,client]);
 const realQuery=db.query.bind(db);let signal!:()=>void,release!:()=>void;const paused=new Promise<void>(r=>signal=r),resume=new Promise<void>(r=>release=r);
 db.query=async<T>(sql:string,params?:unknown[])=>{if(sql==='SELECT id FROM clients WHERE email = $1'&&params?.[0]==='race@example.test'){signal();await resume;}return realQuery<T>(sql,params);};
 const running=req('/auth/verify-email',{token:raceToken.token});await paused;const changed=await req('/portal/account/password',{currentPassword:'New-password-123',newPassword:'Third-password-123'},raceSession.token);release();const raced=await running;db.query=realQuery;const [raceState]=await db.query<{email:string}>('SELECT email FROM clients WHERE id=$1',[client]);check('batch04 in-flight email confirmation cannot undo password cancellation',changed.status===200&&raced.status===400&&raceState.email==='batch04@example.test',{change:changed.status,verify:raced.status,email:raceState.email});
 await db.query("INSERT INTO sessions(token_hash,client_id,expires_at) VALUES($1,$2,now()+interval '1 day') ON CONFLICT(token_hash) DO NOTHING",[session.tokenHash,client]);await db.query("UPDATE orders SET package='CONVERT' WHERE id=$1",[order]);const eligibility=await req(`/portal/services/s-election?company=${order}`,{}),eligibilityBody=await eligibility.json();check('batch04 161: S election purchase describes paid formation order',eligibility.status===400&&eligibilityBody.error?.message==='The S election package is available only with a paid new-LLC formation order through us.',eligibilityBody);
 await db.query("UPDATE orders SET package='NEW',formed_at=now() WHERE id=$1",[order]);const duplicates: {status:number;message:string}[]=[];
 for(const [type,details,route,body]of [['s-election',{},'s-election',{}],['certificate-of-status',{},'certificate',{kind:'certificate-of-status'}],['certified-copy',{},'certificate',{kind:'certified-copy'}],['ein',{target:'company'},'ein',{target:'company'}],['ein',{target:'series',seriesName:'Batch Four LLC - PS 1'},'ein',{target:'series',seriesName:'Batch Four LLC - PS 1'}]]as const){await db.query("INSERT INTO service_orders(client_id,type,llc_name,details,status,amount_cents,formation_order_id) VALUES($1,$2,'Batch Four LLC',$3,'in_progress',0,$4)",[client,type,JSON.stringify(details),order]);const r=await req(`/portal/services/${route}?company=${order}`,body);duplicates.push({status:r.status,message:(await r.json()).error?.message});}
 check('batch04 157: duplicate orders name their section',duplicates.every(x=>x.status===400&&x.message?.includes('See Orders in progress.')&&!x.message.includes('below')),duplicates);
 const expired=await req('/auth/set-password',{token:'invalid-token-fixture',password:'Example-1234'}),expiredBody=await expired.json(),welcome=email.welcomeEmail('Client','http://localhost/set'),warning=email.passwordChangedEmail('http://localhost/portal');check('batch04 205: reset instructions match the visible link',[welcome.html,warning.html,expiredBody.error?.message??''].every(x=>x.includes('Forgot your password?'))&&readFileSync('src/pages/portal/PortalLogin.tsx','utf8').includes('Forgot your password?'),{welcome:welcome.html,warning:warning.html,expired:expiredBody});
 const [unrelatedState]=await db.query<{pending_email:string}>('SELECT pending_email FROM clients WHERE id=$1',[unrelated]);const [unrelatedLink]=await db.query<{used_at:unknown}>('SELECT used_at FROM auth_tokens WHERE token_hash=$1',[unrelatedToken.tokenHash]);check('batch04 password changes leave other clients pending email intact',unrelatedState.pending_email==='keep@example.test'&&unrelatedLink.used_at===null);
 // A new, authorized email change after password recovery still works.
 const fresh=newToken();await db.query("UPDATE clients SET pending_email='fresh@example.test' WHERE id=$1",[client]);await db.query("INSERT INTO auth_tokens(token_hash,client_id,purpose,payload,expires_at) VALUES($1,$2,'verify_email','fresh@example.test',now()+interval '1 hour')",[fresh.tokenHash,client]);const freshResult=await req('/auth/verify-email',{token:fresh.token});check('batch04 newly requested email change still confirms',freshResult.status===200&&(await freshResult.json()).data?.email==='fresh@example.test');
 globalThis.fetch=originalFetch;
}
if(import.meta.main){if(process.argv.includes('--child'))await child();else{let failed=0;await batch04Checks((label,ok,detail)=>{console.log(JSON.stringify({label,ok,detail}));if(!ok)failed++;});process.exit(failed?1:0);}}
