/** B5-ARTICLES-METADATA and B4-RESTORE-S-ELECTION-SECRET-STATE: actual routes and empty database restore. */
import {mkdtempSync,rmSync,readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {gunzipSync} from 'node:zlib';
import {PDFDocument} from '@cantoo/pdf-lib';
const prefix='B23R:';
const evidence=process.env.BATCH23_RECOVERY_EVIDENCE_DIR;
const report=(label:string,ok:boolean,detail?:unknown)=>console.log(prefix+JSON.stringify({label:`batch23 ${label}`,ok,detail}));
const retain=(name:string,text:string)=>{if(evidence){mkdirSync(evidence,{recursive:true});writeFileSync(join(evidence,name),text);}};
async function main(){
 const dir=mkdtempSync(join(tmpdir(),'batch23-recovery-'));
 try{const child=Bun.spawn(['bun',import.meta.filename,'--child'],{cwd:process.cwd(),env:{...process.env,E2E_OFFLINE:'1',VERCEL:'',DEV_PG_DIR:join(dir,'db'),DEV_STORAGE_DIR:join(dir,'files'),DEV_MIRROR_DIR:join(dir,'mirror'),BATCH23_DIR:dir},stdout:'pipe',stderr:'pipe'});
 const[out,err,exit]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);retain('stdout.log',out);retain('stderr.log',err);const rows=out.split('\n').filter(l=>l.startsWith(prefix)).map(l=>JSON.parse(l.slice(prefix.length)));rows.forEach(r=>console.log(JSON.stringify(r)));if(exit||rows.length!==25)throw new Error(`Fixture failed ${exit}, ${rows.length} rows\n${out}\n${err}`);console.log(`${rows.filter(r=>r.ok).length}/${rows.length} Batch 23 recovery checks passed`);process.exitCode=rows.some(r=>!r.ok)?1:0;
 }finally{rmSync(dir,{recursive:true,force:true});}
}
async function runtime(){
 const{app}=await import('./app'),{getDb}=await import('./db'),{env}=await import('./env'),{newToken}=await import('./crypto');const proof=await(await app.request('/api/dev/env-summary')).json();if(!proof.data?.offline||Object.values(proof.data.externals).some(Boolean))throw new Error('Offline proof failed');
 const mails:{to:string[];subject:string;html:string}[]=[];globalThis.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{if(String(input)!=='https://api.resend.com/emails')throw new Error('Unexpected network '+input);mails.push(JSON.parse(String(init?.body)));return process.env.BATCH23_FAIL_MAIL==='1'?new Response('Fixture refusal',{status:503}):Response.json({id:'fixture-accepted'});})as typeof fetch;env.RESEND_API_KEY='fixture-only';
 const db=await getDb(),admin=newToken();const req=(path:string,method='GET',body?:unknown,cookie=`fpsllc_admin=${admin.token}`)=>app.request('/api'+path,{method,headers:{Cookie:cookie,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});return{db,admin,newToken,req,mails};
}
async function child(){
 const{db,admin,newToken,req}=await runtime(),{encryptSecret}=await import('./crypto'),{putFile,readFileStream}=await import('./storage');const client=crypto.randomUUID(),date=new Date(Date.now()-5*86400000).toISOString().slice(0,10);await db.query("INSERT INTO clients(id,email,name)VALUES($1,'current23@example.test','Recovery Client')",[client]);await db.query("INSERT INTO sessions(token_hash,is_admin,expires_at)VALUES($1,true,now()+interval '1 day')",[admin.tokenHash]);
 const company=async(signed:string)=>{const id=crypto.randomUUID(),name=`Recovery ${signed} LLC`,payload={filingPath:'NEW',llcName:{finalName:name},certifications:{articlesSignedBy:signed},management:{structure:'MEMBER_MANAGED'},principalOfficeAddress:{address1:'100 Main Street',city:'Miami',state:'FL',zip:'33101'},members:{memberList:[{firstName:'Recovery',lastName:'Client',address1:'100 Main Street',city:'Miami',state:'FL',zip:'33101'}]},series:[],registeredAgent:{choice:'OWN'}};await db.query("INSERT INTO orders(id,client_id,contact_name,contact_email,package,llc_name,payload,service_fee_cents,state_fees_cents,total_cents,status,paid_at,formed_at)VALUES($1,$2,'Recovery Client','original23@example.test','NEW',$3,$4,0,0,0,'formed',now(),now())",[id,client,name,JSON.stringify(payload)]);return{id,name};};
 const pdfdoc=await PDFDocument.create();pdfdoc.addPage();const pdf=await pdfdoc.save(),file=()=>new File([new Uint8Array(pdf)],'fixture.pdf',{type:'application/pdf'});
 for(const signed of ['CLIENT','SERVICE']){const co=await company(signed),old='L26000123456',corrected='L26000987654',stored=await putFile('articles.pdf',new Uint8Array(pdf).buffer,'application/pdf');await db.query("INSERT INTO documents(client_id,order_id,kind,title,storage_key,content_type,size_bytes,meta)VALUES($1,$2,'articles','Articles',$3,'application/pdf',$4,$5)",[client,co.id,stored.storageKey,pdf.length,JSON.stringify({documentNumber:old})]);
 const form=(number?:string)=>{const f=new FormData();f.set('articles',file());f.set('psd',file());f.set('psdSeries','[]');if(number!==undefined)f.set('documentNumber',number);return f;};const number=async()=>(await db.query<{meta:{documentNumber?:string}}>("SELECT meta FROM documents WHERE order_id=$1 AND kind='articles'",[co.id]))[0]?.meta.documentNumber;
 const kept=await req(`/admin/orders/${co.id}/formation-documents`,'POST',form());report(`B5-ARTICLES-METADATA ${signed} omitted number preserved`,kept.status===200&&await number()===old,{status:kept.status,number:await number()});
 const change=await req(`/admin/orders/${co.id}/formation-documents`,'POST',form(corrected));report(`B5-ARTICLES-METADATA ${signed} corrected number saved`,change.status===200&&await number()===corrected,{status:change.status,number:await number()});
 const before=JSON.stringify(await db.query('SELECT * FROM documents WHERE order_id=$1 ORDER BY id',[co.id]));const bad=await req(`/admin/orders/${co.id}/formation-documents`,'POST',form('BAD NUMBER'));report(`B5-ARTICLES-METADATA ${signed} invalid correction refused before document writes`,bad.status===400&&before===JSON.stringify(await db.query('SELECT * FROM documents WHERE order_id=$1 ORDER BY id',[co.id])),{status:bad.status});
 const view=await(await req(`/admin/orders/${co.id}`)).json();report(`B5-ARTICLES-METADATA ${signed} office sees corrected number`,view.data?.documentNumber===corrected,{number:view.data?.documentNumber});if(signed==='SERVICE'){const st=await db.query<{meta:{documentNumber?:string}}>("SELECT meta FROM documents WHERE order_id=$1 AND kind='statement'",[co.id]);report('B5-ARTICLES-METADATA Statement agrees with corrected Articles',st.length===1&&st[0].meta.documentNumber===corrected,st);}}
 const co=await company('Recovery'),other=await company('Other'),token=newToken();await db.query("INSERT INTO sessions(token_hash,client_id,expires_at)VALUES($1,$2,now()+interval '1 day')",[token.tokenHash,client]);
 const details={ein:'',einPending:true,dateIncorporated:date,effectiveDate:date,officerName:'Recovery Client',officerTitle:'Member',phone:'3055550100',shareholders:[{name:'Recovery Client',address:'100 Main Street, Miami FL 33101',percentage:100,dateAcquired:date,ssnLast4:'6789',joint:'tbe',name2:'Second Owner',ssnLast4Second:'4321'}]},ids:Record<string,string>={};
 for(const state of ['pending','already-flagged','fulfilled','cancelled','deleted','blank','other-company']){const id=ids[state]=crypto.randomUUID(),status=state==='fulfilled'?'fulfilled':state==='cancelled'?'cancelled':state==='blank'?'awaiting_info':'in_progress';await db.query("INSERT INTO service_orders(id,client_id,formation_order_id,type,status,llc_name,details,amount_cents,paid_at,ein_secret,fulfilled_at)VALUES($1,$2,$3,'s-election',$4,'Recovery LLC',$5,0,now(),$6,CASE WHEN $4='fulfilled' THEN now() ELSE NULL END)",[id,client,state==='other-company'?other.id:co.id,status,JSON.stringify(state==='blank'?{}:{...details,...(state==='deleted'?{documentDeletedAt:date}:{}),...(state==='already-flagged'?{taxpayerNumbersRequired:true,taxpayerNumbersNoticeAt:date}:{})}),encryptSecret(JSON.stringify(['123456789|321654321']))]);}
 const ein=ids.ein=crypto.randomUUID();await db.query("INSERT INTO service_orders(id,client_id,formation_order_id,type,status,llc_name,details,amount_cents,paid_at)VALUES($1,$2,$3,'ein','in_progress','Recovery LLC','{}',0,now())",[ein,client,co.id]);
 const{runDbBackup,listBackups}=await import('./backup');const snap=await runDbBackup(),hit=(await listBackups()).find(b=>b.key===snap.key)!,dump=JSON.parse(gunzipSync(Buffer.from(await readFileStream(hit.storageKey))).toString());report('B4-RESTORE-S-ELECTION-SECRET-STATE backup excludes all temporary numbers',dump.tables.service_orders.every((s:{ein_secret:unknown})=>s.ein_secret===null)&&!JSON.stringify(dump).includes('123456789|321654321'));
 const dir=process.env.BATCH23_DIR!;writeFileSync(join(dir,'dump.json'),JSON.stringify(dump));writeFileSync(join(dir,'want.json'),JSON.stringify({client,co,other,ids,date,token:token.token,admin:admin.token,details}));
 for(const fail of [false,true]){const cp=Bun.spawn(['bun',import.meta.filename,'--restore'],{cwd:process.cwd(),env:{...process.env,DEV_PG_DIR:join(dir,fail?'restored-fail':'restored'),BATCH23_FAIL_MAIL:fail?'1':'0'},stdout:'pipe',stderr:'pipe'});const[out,err,code]=await Promise.all([new Response(cp.stdout).text(),new Response(cp.stderr).text(),cp.exited]);retain(`restore-${fail}-stdout.log`,out);retain(`restore-${fail}-stderr.log`,err);out.split('\n').filter(l=>l.startsWith(prefix)).forEach(l=>console.log(l));if(code)throw new Error(`Restore fixture ${code}\n${out}\n${err}`);}
}
async function restored(){
 const{db,req,mails,admin:restoredAdmin,newToken}=await runtime(),{restoreBackup}=await import('./restore'),dir=process.env.BATCH23_DIR!,want=JSON.parse(readFileSync(join(dir,'want.json'),'utf8')),dump=JSON.parse(readFileSync(join(dir,'dump.json'),'utf8'));
 const result=await restoreBackup(db,dump);const restoredToken=newToken();await db.query("INSERT INTO sessions(token_hash,client_id,is_admin,expires_at)VALUES($1,$2,false,now()+interval '1 day'),($3,NULL,true,now()+interval '1 day')",[restoredToken.tokenHash,want.client,restoredAdmin.tokenHash]);
 const cookie=`fpsllc_session=${restoredToken.token}`,admin=`fpsllc_admin=${restoredAdmin.token}`;
 const fulfillEin=async()=>{const pdfdoc=await PDFDocument.create();pdfdoc.addPage();const pdf=await pdfdoc.save(),f=new FormData();f.set('file',new File([new Uint8Array(pdf)],'EIN.pdf',{type:'application/pdf'}));f.set('ein','881234567');f.set('notify','false');return req(`/admin/services/${want.ids.ein}/fulfill`,'POST',f,admin);};
 const row=async(id:string)=>(await db.query<{status:string;details:Record<string,unknown>;ein_secret:string|null}>('SELECT status,details,ein_secret FROM service_orders WHERE id=$1',[id]))[0],pending=await row(want.ids.pending);
 if(process.env.BATCH23_FAIL_MAIL==='1'){const n=(result as unknown as {recoveryNotifications?:{sent:number;failed:number}}).recoveryNotifications;report('B4-RESTORE-S-ELECTION-SECRET-STATE failed email leaves restored records actionable',pending.status==='awaiting_info'&&pending.details.taxpayerNumbersRequired===true&&n?.failed===3&&n.sent===0,{result,pending});report('B4-RESTORE-S-ELECTION-SECRET-STATE failed email never marked sent',!pending.details.taxpayerNumbersNoticeAt,pending.details);process.env.BATCH23_FAIL_MAIL='0';const retry=await fulfillEin(),retried=await row(want.ids.pending);report('B4-RESTORE-S-ELECTION-SECRET-STATE failed restore email retries when EIN arrives',retry.status===200&&!!retried.details.taxpayerNumbersNoticeAt&&retried.details.ein==='881234567'&&retried.status==='awaiting_info',{status:retry.status,details:retried.details});return;}
 report('B4-RESTORE-S-ELECTION-SECRET-STATE pending never-generated package requests reentry',pending.status==='awaiting_info'&&pending.details.taxpayerNumbersRequired===true&&pending.ein_secret===null,pending);
 const sh=pending.details.shareholders as {name:string;ssnLast4?:string;ssnLast4Second?:string}[];report('B4-RESTORE-S-ELECTION-SECRET-STATE preserves answers but clears both on-file hints',sh[0].name==='Recovery Client'&&!sh[0].ssnLast4&&!sh[0].ssnLast4Second,sh);
 report('B4-RESTORE-S-ELECTION-SECRET-STATE automatic email directs reentry at current address without secrets',mails.length===3&&mails.every(m=>m.to[0]==='current23@example.test'&&m.html.includes('Re-enter taxpayer numbers')&&m.html.includes('/portal')&&!m.html.includes('support@')&&!m.html.includes('123456789')&&!m.html.includes('321654321')),mails);retain('recovery-email.html',mails[0]?.html??'NO EMAIL');
 const excluded=await Promise.all(['fulfilled','cancelled','deleted','blank'].map(k=>row(want.ids[k])));report('B4-RESTORE-S-ELECTION-SECRET-STATE fulfilled cancelled deleted and unstarted unchanged',excluded.every(r=>!r.details.taxpayerNumbersRequired)&&excluded[0].status==='fulfilled'&&excluded[1].status==='cancelled',excluded);
 const portal=await(await req(`/portal/services?company=${want.co.id}`,'GET',undefined,cookie)).json();const shown=portal.data?.orders.find((o:{id:string})=>o.id===want.ids.pending);report('B4-RESTORE-S-ELECTION-SECRET-STATE actual portal returns recovery action',shown?.status==='awaiting_info'&&shown.details.taxpayerNumbersRequired===true,shown);retain('restored-portal.json',JSON.stringify(portal,null,2));
 const never=crypto.randomUUID();await db.query("INSERT INTO service_orders(id,client_id,formation_order_id,type,status,llc_name,details,amount_cents,paid_at)VALUES($1,$2,$3,'s-election','in_progress','Never Generated LLC',$4,0,now())",[never,want.client,want.co.id,JSON.stringify(want.details)]);const mailCountBefore=mails.length;
 const otherBefore=JSON.stringify(await row(want.ids['other-company']));const fulfilled=await fulfillEin(),updated=await row(want.ids.pending);report('B4-RESTORE-S-ELECTION-SECRET-STATE EIN arrival saves issued EIN and requests missing numbers',fulfilled.status===200&&updated.details.ein==='881234567'&&updated.details.einPending===false&&updated.status==='awaiting_info'&&updated.details.taxpayerNumbersRequired===true,{status:fulfilled.status,updated});const neverUpdated=await row(never);report('B4-RESTORE-S-ELECTION-SECRET-STATE direct EIN arrival flags and emails never-generated unflagged order',neverUpdated.status==='awaiting_info'&&neverUpdated.details.taxpayerNumbersRequired===true&&neverUpdated.details.ein==='881234567'&&!!neverUpdated.details.taxpayerNumbersNoticeAt&&mails.length===mailCountBefore+1,{neverUpdated,newMails:mails.slice(mailCountBefore)});report('B4-RESTORE-S-ELECTION-SECRET-STATE EIN arrival does not touch other company',otherBefore===JSON.stringify(await row(want.ids['other-company'])));
 const body={ein:'881234567',einPending:false,formationDate:want.date,effectiveDate:want.date,officerName:'Recovery Client',officerTitle:'Member',phone:'3055550100',timingAcknowledged:true,eligibilityAcknowledged:true,certified:true,shareholders:[{name:'Recovery Client',address:'100 Main Street, Miami FL 33101',percentage:100,dateAcquired:want.date,ssn:'',joint:'tbe',name2:'Second Owner',ssn2:''}]};const blank=await req(`/portal/services/${want.ids.pending}/s-election-details`,'POST',body,cookie);const blankError=await blank.json();report('B4-RESTORE-S-ELECTION-SECRET-STATE actual blank SSNs refused',blank.status===400&&blankError.error?.message==="Each owner's SSN must be 9 digits.",{status:blank.status,blankError});const done=await req(`/portal/services/${want.ids.pending}/s-election-details`,'POST',{...body,shareholders:[{...body.shareholders[0],ssn:'123456789',ssn2:'321654321'}]},cookie),answer=await done.json(),saved=await row(want.ids.pending);report('B4-RESTORE-S-ELECTION-SECRET-STATE reentry generates package and clears recovery flag',done.status===200&&!!answer.data?.documentId&&saved.status==='fulfilled'&&saved.details.ein==='881234567'&&!saved.details.taxpayerNumbersRequired,{status:done.status,answer,saved:{status:saved.status,details:saved.details}});const doc=answer.data?.documentId?(await db.query<{order_id:string;storage_key:string;meta:{sensitive:boolean}}>('SELECT order_id,storage_key,meta FROM documents WHERE id=$1',[answer.data.documentId]))[0]:null;const raw=doc?readFileSync(join(process.env.DEV_STORAGE_DIR!,doc.storage_key.slice(4))):Buffer.alloc(0);const downloaded=answer.data?.documentId?await req(`/portal/documents/${answer.data.documentId}/download`,'GET',undefined,cookie):null;report('B4-RESTORE-S-ELECTION-SECRET-STATE generated document encrypted and company scoped',doc?.order_id===want.co.id&&doc?.meta.sensitive===true&&raw.toString().startsWith('FPSLLC-ENC-1')&&downloaded?.status===200&&Buffer.from(await downloaded.arrayBuffer()).toString('ascii',0,5)==='%PDF-',doc);
 report('B4-RESTORE-S-ELECTION-SECRET-STATE no taxpayer numbers in any email',mails.every(m=>!m.html.includes('123456789')&&!m.html.includes('321654321')));
}
if(import.meta.main){if(process.argv.includes('--child'))await child();else if(process.argv.includes('--restore'))await restored();else await main();}
