/** Batch29: actual form validators, Chromium components, and authenticated generation route. */
import{mkdtempSync,rmSync,readFileSync,mkdirSync,writeFileSync}from'node:fs';import{join}from'node:path';import{tmpdir}from'node:os';
type Report=(label:string,ok:boolean,detail?:unknown)=>void;
async function child(){
 const report:Report=(label,ok,detail)=>console.log('B29:'+JSON.stringify({label,ok,detail}));
 const {defaultFormData}=await import('../src/components/forms/florida-llc/defaults');const{buildPayload}=await import('../src/components/forms/florida-llc/buildPayload');const{validateStep}=await import('../src/components/forms/florida-llc/stepValidation');const{orderFormSchema}=await import('./validation');const nameRules=await import('../src/components/forms/florida-llc/validation');const seriesDedupeKey=(nameRules as {seriesConflictKey?:(s:string)=>string;seriesDedupeKey:(s:string)=>string}).seriesConflictKey ?? nameRules.seriesDedupeKey;
 // Existing e2e's real valid payload, without importing its executable runner.
 const source=readFileSync(join(import.meta.dir,'e2e.ts'),'utf8');const start=source.indexOf('const formData: FloridaLLCFormData = ')+'const formData: FloridaLLCFormData = '.length;const end=source.indexOf('\n};',start)+2;const form=new Function('defaultFormData','testEmail','return ('+source.slice(start,end)+')')(defaultFormData,'batch29@example.test');
 const issues=(v:unknown)=>{const r=orderFormSchema.safeParse(v);return r.success?[]:r.error.issues.map(i=>i.path.join('.'));};
 const valid=orderFormSchema.safeParse(form);const unchecked={...form,registeredAgentSeriesAgreementAcknowledgment:false};const other={...form,registeredAgentFirstName:'Other',registeredAgentAcceptanceName:'Other Member, Jr.',registeredAgentElectronicSignature:'Other Member, Jr.'};const payload=buildPayload(form);
 const personal=issues(other).includes('registeredAgentFirstName'),required=issues(unchecked).includes('registeredAgentSeriesAgreementAcknowledgment'),ui=!!validateStep('certify',unchecked).registeredAgentSeriesAgreementAcknowledgment;
 const retained={...form,filingPath:'CONVERT',existingLlcName:'Existing LLC',sunbizDocumentNumber:'L26000000001',registeredAgentType:'ENTITY',registeredAgentBusinessEntityName:'Existing Agent LLC',conversionAuthorityAcknowledgment:true};
 const agentSchemaOk=valid.success&&personal&&required&&ui&&payload.acknowledgments.registeredAgentSeriesAgreementAcknowledgment===true&&!issues(retained).includes('registeredAgentFirstName');
 const same=[['PS Alpha & Beta','P.S. Alpha and Beta'],['PS Rentals','PS Rental'],['PS Blue-Lake','PS Blue Lake'],['PS The Harbor','PS Harbor']];const different=[['PS A','PS B'],['PS 1','PS 2'],['PS Alpha','PS Beta']];
 const collision={...form,series:[{id:'a',name:same[0][0]},{id:'b',name:same[0][1]}]};report('B02',same.every(([a,b])=>seriesDedupeKey(a)===seriesDedupeKey(b))&&different.every(([a,b])=>seriesDedupeKey(a)!==seriesDedupeKey(b))&&!!validateStep('series',collision)['series.1.name']&&issues(collision).includes('series'),{same:same.map(([a,b])=>[seriesDedupeKey(a),seriesDedupeKey(b)])});
 const {batch29Browser}=await import('../scripts/batch29-portal-check');await batch29Browser(report);
 const held={...form,nameCheck:{key:'E2E COASTAL HOLDINGS | E2E COASTAL BACKUP',available:true,results:[{verdict:'held'},{verdict:'clear'}]}};const words=JSON.stringify(validateStep('name',held));const server=readFileSync(join(import.meta.dir,'routes-payments.ts'),'utf8'),mirror=readFileSync(join(import.meta.dir,'sunbiz.ts'),'utf8');report('B09',words.includes('recently inactive')&&!words.includes('recently dissolved')&&server.includes('recently inactive company')&&mirror.includes('recently inactive — our service conservatively')&&readFileSync(join(import.meta.dir,'../src/components/forms/florida-llc/NameCheck.tsx'),'utf8').includes('recently inactive company. Our service conservatively'),{words});
 const{app}=await import('./app'),{getDb}=await import('./db'),{newToken}=await import('./crypto'),{rateLimit}=await import('./auth');const proof=await(await app.request('/api/dev/env-summary')).json();if(!proof.data.offline||Object.values(proof.data.externals).some(Boolean))throw Error('Offline proof failed');const db=await getDb(),cid=crypto.randomUUID(),co=crypto.randomUUID(),token=newToken();
 const orderRequest=(body:unknown)=>app.request('/api/orders',{method:'POST',headers:{'Content-Type':'application/json','X-Forwarded-For':'10.29.1.1'},body:JSON.stringify(body)});
 const refusedOrder=await orderRequest(unchecked),otherOrder=await orderRequest(other),acceptedOrder=await orderRequest(form);const acceptedBody=await acceptedOrder.json();const storedOrder=acceptedBody.data?.orderId?(await db.query<{payload:{acknowledgments?:{registeredAgentSeriesAgreementAcknowledgment?:boolean}}|string}>('SELECT payload FROM orders WHERE id=$1',[acceptedBody.data.orderId]))[0]:null;const stored=typeof storedOrder?.payload==='string'?JSON.parse(storedOrder.payload):storedOrder?.payload;
 report('B01',agentSchemaOk&&refusedOrder.status===400&&otherOrder.status===400&&acceptedOrder.status===200&&stored?.acknowledgments?.registeredAgentSeriesAgreementAcknowledgment===true,{agentSchemaOk,refused:refusedOrder.status,other:otherOrder.status,accepted:acceptedOrder.status,acceptedBody,storedAcknowledgments:stored?.acknowledgments});
 await db.query("INSERT INTO clients(id,email,name) VALUES($1,'generation29@example.test','Jane Owner')",[cid]);await db.query("INSERT INTO sessions(token_hash,client_id,expires_at) VALUES($1,$2,now()+interval '1 day')",[token.tokenHash,cid]);
 const op={filingPath:'NEW',llcName:{finalName:'Numbering LLC'},principalOfficeAddress:{address1:'100 Main Street',city:'Miami',state:'FL',zip:'33101'},management:{structure:'MEMBER_MANAGED'},members:{memberList:[{firstName:'Jane',lastName:'Owner',address1:'100 Main Street',city:'Miami',state:'FL',zip:'33101'}]},series:[],registeredAgent:{choice:'SERVICE'}};
 await db.query("INSERT INTO orders(id,client_id,contact_name,contact_email,package,llc_name,payload,service_fee_cents,state_fees_cents,total_cents,status,paid_at,formed_at) VALUES($1,$2,'Jane Owner','generation29@example.test','NEW','Numbering LLC',$3,0,0,0,'formed',now(),now())",[co,cid,JSON.stringify(op)]);
 const answers={firstOrAmended:'first',effectiveDate:'2026-09-20',authorized:true,multiOwner:false,ownershipMode:'percent',members:[{id:crypto.randomUUID(),name:'Jane Owner',address:'100 Main Street, Miami FL 33101',percentage:100}],series:[],includeCapitalCalls:false,competition:'B',includeShotgun:false,borrowingThreshold:50000,assets:[]};
 const req=(a:unknown)=>app.request('/api/portal/oa/generate?company='+co,{method:'POST',headers:{Cookie:'fpsllc_session='+token.token,'Content-Type':'application/json'},body:JSON.stringify(a)});const seq=async()=>Number((await db.query<{oa_generation_seq:number}>('SELECT oa_generation_seq FROM clients WHERE id=$1',[cid]))[0].oa_generation_seq);
 const invalid=await req({...answers,members:[{...answers.members[0],isEntity:true,signerName:'',signerTitle:''}]});const afterInvalid=await seq();const good=await req(answers);const goodBody=await good.json();const afterGood=await seq();for(let i=0;i<10;i++)await rateLimit('oagen:'+cid,10,3600000);const limited=await req(answers);const afterLimited=await seq();report('B08',invalid.status===400&&afterInvalid===0&&good.status===200&&afterGood===1&&limited.status===429&&afterLimited===1,{invalid:invalid.status,afterInvalid,good:good.status,goodBody,afterGood,limited:limited.status,afterLimited});
}
export async function batch29Checks(report:Report){const dir=mkdtempSync(join(tmpdir(),'batch29-'));try{const p=Bun.spawn([process.execPath,import.meta.filename,'--child'],{env:{...process.env,E2E_OFFLINE:'1',VERCEL:'',DEV_PG_DIR:join(dir,'db'),DEV_STORAGE_DIR:join(dir,'files'),DEV_MIRROR_DIR:join(dir,'mirror')},stdout:'pipe',stderr:'pipe'});const[out,err,code]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);const rows=out.split('\n').filter(l=>l.startsWith('B29:')).map(l=>JSON.parse(l.slice(4)));for(let i=1;i<=9;i++){const label='B'+String(i).padStart(2,'0'),r=rows.find(r=>r.label===label);const extraOk=(label!=='B01'||rows.find(x=>x.label==='personal-agent-ui')?.ok===true)&&(label!=='B09'||rows.find(x=>x.label==='name-result-ui')?.ok===true);const isolated=rows.find(x=>x.label==='browser-isolation')?.ok===true;report('batch29 '+label,code===0&&r?.ok===true&&extraOk&&isolated,r?.detail??{code,out,err});}if(process.env.BATCH29_EVIDENCE_DIR){mkdirSync(process.env.BATCH29_EVIDENCE_DIR,{recursive:true});writeFileSync(join(process.env.BATCH29_EVIDENCE_DIR,'runtime.json'),JSON.stringify({code,rows,out,err},null,2));}}finally{rmSync(dir,{recursive:true,force:true});}}
if(import.meta.main){if(process.argv.includes('--child'))await child();else{let failed=0;await batch29Checks((label,ok,detail)=>{console.log(JSON.stringify({label,ok,detail}));if(!ok)failed++;});process.exitCode=failed?1:0;}}
