/** Authenticated real routes and delivered PDFs in a throwaway offline database. */
import {mkdtempSync,rmSync,writeFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';import {tmpdir} from 'node:os';
type Report=(label:string,ok:boolean,detail?:unknown)=>void;
async function child(){
 const {app}=await import('./app'),{getDb}=await import('./db'),{newToken}=await import('./crypto');
 const proof=await(await app.request('/api/dev/env-summary')).json();if(!proof.data.offline||Object.values(proof.data.externals).some(Boolean))throw Error('Not offline');
 const db=await getDb(),client=crypto.randomUUID(),company=crypto.randomUUID(),other=crypto.randomUUID(),outsider=crypto.randomUUID(),otherClient=crypto.randomUUID(),token=newToken();
 const old=crypto.randomUUID(),draft=crypto.randomUUID(),foreign=crypto.randomUUID(),legacy=crypto.randomUUID(),stolen=crypto.randomUUID();
 for(const id of [client,otherClient])await db.query("INSERT INTO clients(id,email,name) VALUES($1,$2,'Test Owner')",[id,`${id}@example.test`]);
 await db.query("INSERT INTO sessions(token_hash,client_id,expires_at) VALUES($1,$2,now()+interval '1 day')",[token.tokenHash,client]);
 for(const [id,owner] of [[company,client],[other,client],[outsider,otherClient]])await db.query("INSERT INTO orders(id,client_id,contact_name,contact_email,package,llc_name,payload,service_fee_cents,state_fees_cents,total_cents,status,paid_at,formed_at) VALUES($1,$2,'Test Owner','test@example.test','NEW','Selection LLC',$3,0,0,0,'formed',now(),now())",[id,owner,JSON.stringify({filingPath:'NEW',llcName:{finalName:'Selection LLC'},management:{structure:'MEMBER_MANAGED'},members:{memberList:[{firstName:'Intake',lastName:'Owner'}]},series:[]})]);
 const member=(name:string)=>({name,address:'101 Main Street',percentage:100,contribution:'',todBeneficiary:''});
 const inputs={version:'multi',companyName:'Selection LLC',principalAddress:'101 Main Street',effectiveDate:'January 2, 2026',amendedRestated:false,priorAgreementDate:null,managerNames:['Management LLC'],managerEntitySigners:[{manager:'Management LLC',name:'Martha Manager',title:'President'}],members:[{...member('Holding LLC'),percentage:50,entitySigner:{name:'Helen Holder',title:'President'}},{...member('Alice Owner and Ben Owner'),percentage:50,signatories:['Alice Owner','Ben Owner'],jointHolding:'tenants by the entirety'}],series:[]};
 for(const [id,owner,co,data,n] of [[old,client,company,inputs,1],[draft,client,company,{...inputs,members:[member('Draft Stranger')],managerNames:['Draft Manager'],managerEntitySigners:[]},2],[foreign,client,other,inputs,3],[legacy,client,null,inputs,4],[stolen,otherClient,outsider,inputs,5]] as const)await db.query("INSERT INTO oa_generations(id,client_id,order_id,template_version,amended_restated,inputs,generation_number,created_at) VALUES($1,$2,$3,'test',false,$4,$5,now()+$6::integer*interval '1 second')",[id,owner,co,JSON.stringify(data),n,id===legacy?0:n]);
 await db.query("INSERT INTO oa_profiles(client_id,order_id,answers,rev) VALUES($1,$2,$3,1)",[client,company,JSON.stringify({members:[{name:'Unfinished Edit',address:'101 Main St',percentage:100}],managers:[{name:'Unfinished Manager'}]})]);
 const request=(path:string,body?:unknown)=>app.request('/api'+path,{method:body===undefined?'GET':'POST',headers:{Cookie:`fpsllc_session=${token.token}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 const post=async(path:string,body:unknown)=>{const r=await request(path,body);return{status:r.status,body:await r.json()};};
 let jointPagesOk=true;
 const pdf=async(id:string,name:string)=>{const r=await request('/portal/documents/'+id+'/download');const bytes=new Uint8Array(await r.arrayBuffer());if(!r.ok)throw Error('Download failed '+r.status);if(process.env.BATCH30_EVIDENCE_DIR){mkdirSync(process.env.BATCH30_EVIDENCE_DIR,{recursive:true});writeFileSync(join(process.env.BATCH30_EVIDENCE_DIR,name+'.pdf'),bytes);}const text=Bun.spawnSync(['pdftotext','-layout','-','-'],{stdin:bytes});if(text.exitCode)throw Error('PDF extraction failed');const raw=text.stdout.toString();if(name.startsWith('consent'))for(const page of raw.split('\f'))if(page.includes('tenants by the entirety')){const lines=page.split('\n').map(x=>x.trim());jointPagesOk&&=lines.includes('Alice Owner')&&lines.includes('Ben Owner');}return raw.replace(/\s+/g,' ');};
 const amendment={generationId:old,agreementDate:'2026-01-02',effectiveDate:'2026-09-22',mode:'attached'};
 const a=await post('/portal/oa/amend?company='+company,amendment),text=a.body.data?.documentId?await pdf(a.body.data.documentId,'amendment'):JSON.stringify(a);
 const bad:number[]=[];for(const generationId of [undefined,foreign,legacy,stolen,crypto.randomUUID()])bad.push((await post('/portal/oa/amend?company='+company,{...amendment,generationId})).status);
 const list=await request('/portal/oa/sources?company='+company);const listed=await list.json();
 const report:Report=(label,ok,detail)=>console.log('B30:'+JSON.stringify({label,ok,detail}));
 report('C01',a.status===200&&text.includes('Helen Holder')&&text.includes('Alice Owner')&&text.includes('Ben Owner')&&text.includes('Martha Manager')&&!text.includes('Draft Stranger')&&bad.every(n=>n===400)&&Array.isArray(listed.data)&&listed.data.length===2,{status:a.status,bad,text,listed});
 const consent={company,generationId:old,partiesConfirmed:true,seriesName:'Selection LLC, PS One',seriesNumber:'One',purpose:'',effectiveDate:'2026-09-22'};
 const c=await post('/portal/series/consent',consent),ct=c.body.data?.documentId?await pdf(c.body.data.documentId,'consent-manager'):JSON.stringify(c);
 const refused:number[]=[];for(const patch of [{partiesConfirmed:false},{generationId:undefined},{generationId:foreign},{generationId:legacy},{generationId:stolen}])refused.push((await post('/portal/series/consent',{...consent,...patch})).status);
 // The same selected ownership unit must give both spouses separate signature lines in member-managed exhibits too.
 await db.query('UPDATE oa_generations SET inputs=$1 WHERE id=$2',[JSON.stringify({...inputs,version:'member',managerNames:[],managerEntitySigners:[]}),old]);
 const cm=await post('/portal/series/consent',consent),mt=cm.body.data?.documentId?await pdf(cm.body.data.documentId,'consent-member'):JSON.stringify(cm);
 await db.query('UPDATE oa_generations SET inputs=$1 WHERE id=$2',[JSON.stringify({...inputs,members:[{...inputs.members[0],entitySigner:{name:'',title:''}}]}),old]);
 const incomplete=await post('/portal/series/consent',consent);
 await db.query('DELETE FROM oa_generations WHERE id=$1',[old]);const deleted=await post('/portal/series/consent',consent);
 report('C02',c.status===200&&cm.status===200&&ct.includes('Helen Holder')&&ct.includes('Martha Manager')&&ct.includes('Alice Owner')&&ct.includes('Ben Owner')&&!ct.includes('Unfinished')&&!ct.includes('Draft Stranger')&&mt.includes('tenants by the entirety')&&!mt.includes('Martha Manager')&&refused.every(n=>n===400)&&deleted.status===400&&incomplete.status===400&&jointPagesOk&&!ct.includes('[[signature-group]]'),{status:c.status,member:cm.status,refused,deleted:deleted.status,incomplete:incomplete.status,jointPagesOk,text:ct,memberText:mt});
 const{batch30Browser}=await import('../scripts/batch30-walk');await batch30Browser(report);
}
export async function batch30Checks(report:Report){const dir=mkdtempSync(join(tmpdir(),'batch30-'));try{const p=Bun.spawn([process.execPath,import.meta.filename,'--child'],{env:{...process.env,E2E_OFFLINE:'1',VERCEL:'',DEV_PG_DIR:join(dir,'db'),DEV_STORAGE_DIR:join(dir,'files'),DEV_MIRROR_DIR:join(dir,'mirror')},stdout:'pipe',stderr:'pipe'});const[out,err,code]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);const rows=out.split('\n').filter(s=>s.startsWith('B30:')).map(s=>JSON.parse(s.slice(4)));for(const label of ['C01','C02','C03']){const r=rows.find(x=>x.label===label);const browser=rows.find(x=>x.label===label+'-browser');report('batch30 '+label,code===0&&r?.ok===true&&(label==='C03'||browser?.ok===true),{result:r,browser,code,err:code?err:undefined});}if(process.env.BATCH30_EVIDENCE_DIR){mkdirSync(process.env.BATCH30_EVIDENCE_DIR,{recursive:true});writeFileSync(join(process.env.BATCH30_EVIDENCE_DIR,'runtime.json'),JSON.stringify({rows,code,err},null,2));}}finally{rmSync(dir,{recursive:true,force:true});}}
if(import.meta.main){if(process.argv.includes('--child'))await child();else{let failed=0;await batch30Checks((label,ok,detail)=>{console.log(JSON.stringify({label,ok,detail}));if(!ok)failed++;});process.exitCode=failed?1:0;}}
