import {mkdtempSync,rmSync,writeFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
type Check=(label:string,ok:boolean,detail?:unknown)=>void;
export async function batch41BillingChecks(check:Check){
 const dir=mkdtempSync(join(tmpdir(),'batch41-billing-'));
 try{const p=Bun.spawn(['bun',import.meta.filename,'--child'],{cwd:process.cwd(),env:{...process.env,E2E_OFFLINE:'1',VERCEL:'',DEV_PG_DIR:join(dir,'db'),DEV_STORAGE_DIR:join(dir,'files'),DEV_MIRROR_DIR:join(dir,'mirror')},stdout:'pipe',stderr:'pipe'});
 const [out,err,code]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);
 const rows=out.split('\n').filter(x=>x.startsWith('B41B:')).map(x=>JSON.parse(x.slice(5)));
 for(const group of ['obligations','correspondence']){const own=rows.filter(r=>r.group===group);check(group==='obligations'?'batch41 agent obligations and payment recovery':'batch41 financial correspondence recovery',code===0&&own.length>=5&&own.every(r=>r.ok),{rows:own,exit:code,stderr:code?err:undefined});}
 if(process.env.BATCH41_BILLING_EVIDENCE){mkdirSync(process.env.BATCH41_BILLING_EVIDENCE,{recursive:true});writeFileSync(join(process.env.BATCH41_BILLING_EVIDENCE,'server-raw.log'),out+'\n'+err);writeFileSync(join(process.env.BATCH41_BILLING_EVIDENCE,'server-results.json'),JSON.stringify(rows,null,2));}
 }finally{rmSync(dir,{recursive:true,force:true});}
}
async function child(){
 let failComplete=false;
 let fulfillmentHold:Promise<void>|null=null,fulfillmentEntered:(()=>void)|null=null;
 (globalThis as unknown as {b41Fulfillment:()=>Promise<void>}).b41Fulfillment=async()=>{if(fulfillmentHold){fulfillmentEntered?.();await fulfillmentHold;}};
 let delayed:Promise<void>|null=null,entered:(()=>void)|null=null;
 const calls:{action:string;key?:string}[]=[];
 (globalThis as unknown as {b41Provider:(action:string,opts:{key?:string})=>Promise<void>}).b41Provider=async(action,opts)=>{calls.push({action,key:opts.key});if(action==='complete'&&failComplete){failComplete=false;throw Error('Fixture unknown completion outcome');}if(action==='authorize'&&delayed){entered?.();await delayed;}};
 Bun.plugin({name:'b41-provider-observer',setup(b){b.onLoad({filter:/\/server\/square\.ts$/},async a=>{let s=await Bun.file(a.path).text();const needle="export async function agentSquarePayment(action: 'authorize' | 'get' | 'complete' | 'cancel', opts: { id?: string; key?: string; source?: string; customerId?: string; amount?: number; email?: string; reference?: string; customerInitiated?: boolean }): Promise<AgentPayment> {";if(!s.includes(needle))throw Error('Provider observation point unavailable');s=s.replace(needle,needle+'\n await globalThis.b41Provider(action,opts);');return {contents:s,loader:'ts'};});b.onLoad({filter:/\/server\/renewals\.ts$/},async a=>{let s=await Bun.file(a.path).text();const needle='export async function fulfillPaidRenewal(renewalId:string,paymentId:string|null,simulate?:CardSimulation,cardAlreadySaved=false,automatic=false):Promise<void> {';if(!s.includes(needle))throw Error('Fulfillment observation point unavailable');s=s.replace(needle,needle+'\n await globalThis.b41Fulfillment();');return {contents:s,loader:'ts'};});}});
 const {app}=await import('./app'),{getDb}=await import('./db'),{env}=await import('./env'),{newToken}=await import('./crypto'),{runRenewals}=await import('./renewals');
 const proof=(await(await app.request('/api/dev/env-summary')).json()).data;if(!proof?.offline||Object.values(proof.externals).some(Boolean))throw Error('Offline proof absent');
 console.log('PROOF:'+JSON.stringify({proof,pg:process.env.DEV_PG_DIR,storage:process.env.DEV_STORAGE_DIR}));
 const db=await getDb(),admin=newToken(),user=newToken(),client=crypto.randomUUID();await db.query("INSERT INTO clients(id,email,name) VALUES($1,'billing41@example.test','Billing')",[client]);await db.query("INSERT INTO sessions(token_hash,is_admin,expires_at) VALUES($1,true,now()+interval '1 day')",[admin.tokenHash]);await db.query("INSERT INTO sessions(token_hash,client_id,is_admin,expires_at) VALUES($1,$2,false,now()+interval '1 day')",[user.tokenHash,client]);
 let mailHold:Promise<void>|null=null,mailEntered:(()=>void)|null=null;
 let failMail=false;const mails:{subject:string;html:string}[]=[];env.RESEND_API_KEY='offline-fixture';globalThis.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{if(String(input)!=='https://api.resend.com/emails')throw Error('External request refused');if(failMail)return new Response('Fixture outage',{status:503});if(mailHold){const hold=mailHold;mailHold=null;mailEntered?.();await hold;}mails.push(JSON.parse(String(init?.body)));return Response.json({id:'fixture'});}) as typeof fetch;
 const check=(group:string,label:string,ok:boolean,detail?:unknown)=>console.log('B41B:'+JSON.stringify({group,label,ok,detail}));
 const request=async(path:string,body?:unknown)=>{const r=await app.request('/api/'+path,{method:body===undefined?'GET':'POST',headers:{Cookie:`fpsllc_admin=${admin.token}; fpsllc_session=${user.token}`,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:await r.json()};};
 const company=async(date='2026-09-15')=>{await db.query("UPDATE orders SET status='parked' WHERE status='formed'");failMail=false;mails.length=0;const id=crypto.randomUUID();await db.query("INSERT INTO orders(id,client_id,contact_name,contact_email,package,llc_name,payload,service_fee_cents,state_fees_cents,total_cents,status,paid_at,formed_at,ra_appointment_date,ra_renewal_date,square_customer_id,square_card_id,card_status,card_last4) VALUES($1,$2,'Billing','billing41@example.test','NEW','Billing LLC',$3,0,0,0,'formed',now(),now(),$5,$4,'fixture-customer','fixture-card','on_file','1234')",[id,client,JSON.stringify({registeredAgent:{choice:'SERVICE',renewalCardConsent:true},series:[]}),date,'2025-'+date.slice(5)]);return id;};
 const renewal=async(id:string,date:string,status='declined')=>{const rid=crypto.randomUUID(),token=newToken().token;await db.query("INSERT INTO ra_renewals(id,order_id,renewal_date,charge_due,amount_cents,status,checkout_token,notice_sent_at,link_url) VALUES($1,$2,$3,$3::date-15,9900,$4,$5,now(),$6)",[rid,id,date,status,token,`/agent-checkout?kind=renewal&id=${rid}&token=${token}`]);return {id:rid,path:`agent-checkout/renewal/${rid}?token=${token}`};};
 const order=async(id:string)=>(await db.query<{ra_renewal_date:string}>('SELECT ra_renewal_date::text FROM orders WHERE id=$1',[id]))[0];
 const submit=(id:string,reason='nonpayment',date='2026-09-20')=>request(`admin/orders/${id}/agent`,{action:'submitted',date,reason,note:'Synthetic supporting record'});
 for(const reason of ['nonpayment','inaccurate-contact','unlawful-use']){const id=await company('2026-11-20'),r=await renewal(id,'2026-11-20','notice_sent');await submit(id,reason);const get=await request(r.path),paid=await request(r.path,{sourceId:'offline-credit',consent:true});check('obligations',reason+' cannot sell a future year',get.status===400&&paid.status===400&&(await order(id)).ra_renewal_date==='2026-11-20',{get,paid});}
 for(const state of ['submitted','filed','ended']){const date=state==='ended'?'2026-06-15':'2026-09-15',id=await company(date),r=await renewal(id,date);await submit(id,'nonpayment',state==='ended'?'2026-07-01':'2026-09-20');if(state!=='submitted')await request(`admin/orders/${id}/agent`,{action:'filed',date:state==='ended'?'2026-07-02':'2026-09-22'});const info=await request(r.path);const n=calls.length;const paid=await request(r.path,{sourceId:'offline-credit',consent:true}),again=await request(r.path,{sourceId:'offline-credit',consent:true});check('obligations','arrears when '+state+' settle without renewal',info.body.data?.purpose==='service_fee'&&paid.status===200&&again.status===200&&(await order(id)).ra_renewal_date===date&&calls.slice(n).filter(c=>c.action==='authorize').length===1&&mails.some(m=>m.html.includes('does not renew service'))&&!mails.some(m=>m.subject.startsWith('Registered agent service renewed')),{info,paid,order:await order(id),mails});}
 {const id=await company('2026-11-20'),prior=await renewal(id,'2026-06-15'),future=await renewal(id,'2026-11-20');await request(`admin/orders/${id}/agent`,{action:'cancellation',date:'2026-08-01',note:'Timely next-cycle notice; prior debt remains unpaid'});await submit(id);const owed=await request(prior.path),unavailable=await request(future.path);check('obligations','timely cancellation preserves genuine prior overdue fees',owed.body.data?.purpose==='service_fee'&&unavailable.status===400,{owed,unavailable});}
 {const id=await company(),r=await renewal(id,'2026-09-15');let resume!:()=>void;delayed=new Promise<void>(resolve=>resume=resolve);const reached=new Promise<void>(resolve=>entered=resolve);const pending=request(r.path,{sourceId:'offline-credit',consent:true});await reached;const event=await submit(id);resume();const paid=await pending;delayed=null;const after=await submit(id);check('obligations','in-flight payment is reconciled before resignation',event.status===409&&paid.status===200&&after.status===200,{event,paid,after});}
 for(const via of ['portal','office']){const id=await company('2026-11-20'),r=await renewal(id,'2026-11-20');let resume!:()=>void;fulfillmentHold=new Promise<void>(resolve=>resume=resolve);const reached=new Promise<void>(resolve=>fulfillmentEntered=resolve);const payment=request(r.path,{sourceId:'offline-credit',consent:true});await reached;const notice=via==='portal'?await request('portal/registered-agent/cancel',{company:id}):await request(`admin/orders/${id}/agent`,{action:'cancellation',date:'2026-09-01',note:'Actual earlier cancellation notice'});await runRenewals('2026-09-23');resume();const paid=await payment;fulfillmentHold=null;const [saved]=await db.query<{ra_payment_target:string|null;ra_cancellation_requested_at:unknown;status:string}>("SELECT o.ra_payment_target,o.ra_cancellation_requested_at,r.status FROM orders o JOIN ra_renewals r ON r.order_id=o.id WHERE r.id=$1",[r.id]);check('obligations',via+' cancellation after capture preserves notice and same payment fulfillment',notice.status===200&&paid.status===200&&!!saved.ra_cancellation_requested_at&&saved.status==='paid_by_link'&&saved.ra_payment_target===null,{notice,paid,saved});}
 {const id=await company('2026-11-20'),r=await renewal(id,'2026-11-20');const notice=await request('portal/registered-agent/cancel',{company:id});const n=calls.length,paid=await request(r.path,{sourceId:'offline-credit',consent:true}),resume=await request(r.path,{resume:true});const attempts=await db.query('SELECT id FROM ra_payment_attempts WHERE target_id=$1',[r.id]);check('obligations','new payment after timely notice remains refused including crafted resume',notice.status===200&&paid.status===400&&resume.status===400&&calls.length===n&&attempts.length===0,{notice,paid,resume,attempts});}
 {const id=await company('2026-11-20'),r=await renewal(id,'2026-11-20');const n=calls.length;failComplete=true;const unknown=await request(r.path,{sourceId:'offline-credit',consent:true}),event=await submit(id),replacement=await request(`admin/orders/${id}/agent`,{action:'replacement',date:'2026-09-20',note:'Synthetic proof'}),notice=await request('portal/registered-agent/cancel',{company:id}),info=await request(r.path),portal=await request('portal/companies'),retry=await request(r.path,{resume:true});check('obligations','unknown provider outcome resumes original payment before lifecycle changes',unknown.status===503&&event.status===409&&replacement.status===409&&notice.status===200&&info.status===200&&info.body.data?.reconciling===true&&portal.body.data?.find((o:{orderId:string})=>o.orderId===id)?.renewals?.some((r:{reconcilingPayment?:boolean;linkUrl?:string})=>r.reconcilingPayment&&r.linkUrl)&&retry.status===200&&calls.slice(n).filter(c=>c.action==='authorize').length===1,{unknown,event,replacement,notice,info,retry,calls:calls.slice(n)});}
 {const id=await company(),r=await renewal(id,'2026-09-15');await submit(id);const bad=await request(r.path,{sourceId:'offline-prepaid',consent:true});const fee=(await db.query<{id:string;checkout_token:string}>("SELECT id,checkout_token FROM ra_renewals WHERE order_id=$1 AND purpose='resignation'",[id]))[0];const paid=await request(`agent-checkout/renewal/${fee.id}?token=${fee.checkout_token}`,{sourceId:'offline-credit',consent:true});check('obligations','eligible debt card and separate resignation fee preserved',bad.status===400&&paid.status===200&&(await order(id)).ra_renewal_date==='2026-09-15',{bad,paid});}
 {const id=await company('2030-06-01');failMail=true;await request('dev/renewal-decline',{code:'GENERIC_DECLINE'});await runRenewals('2030-05-17');const [r]=await db.query<{id:string;link_url:string|null;status:string}>('SELECT id,link_url,status FROM ra_renewals WHERE order_id=$1',[id]);check('correspondence','decline stores portal link despite email failure',r.status==='declined'&&!!r.link_url,r);failMail=false;mails.length=0;await runRenewals('2030-05-18');check('correspondence','late reminder describes decline and passed deadline',mails.some(m=>m.html.includes('renewal charge was declined')&&m.html.includes('cancellation deadline for this renewal was'))&&!mails.some(m=>m.html.includes('There is nothing you need to do')),mails);await db.query("UPDATE ra_renewals SET notice_sent_at=NULL WHERE id=$1",[r.id]);mails.length=0;await runRenewals('2030-06-02');check('correspondence','overdue retry does not promise a past payment deadline',mails.some(m=>m.html.includes('now overdue'))&&!mails.some(m=>m.html.includes('Please pay by')),mails);}
 {const id=await company('2030-06-01');failMail=true;await runRenewals('2030-05-17');const [r]=await db.query<{id:string;status:string}>('SELECT id,status FROM ra_renewals WHERE order_id=$1',[id]);const n=calls.length;failMail=false;mails.length=0;await Promise.all([runRenewals('2030-05-18'),runRenewals('2030-05-18')]);check('correspondence','paid previous anniversary sends recovered receipt once',r.status==='charged'&&mails.length===1&&mails[0].html.includes('No further payment is due for this renewal')&&calls.length===n,{r,mails,newCalls:calls.length-n});}
 {await company('2030-06-01');await runRenewals('2030-03-22');mails.length=0;failMail=true;await request('dev/renewal-decline',{code:'GENERIC_DECLINE'});await runRenewals('2030-05-17');failMail=false;await runRenewals('2030-05-18');check('correspondence','failed decline notice retries after earlier reminder succeeded',mails.some(m=>m.html.includes('renewal charge was declined')),mails);}
 {const id=await company('2030-06-01');failMail=true;await request('dev/renewal-decline',{code:'GENERIC_DECLINE'});await runRenewals('2030-05-17');const [r]=await db.query<{id:string;checkout_token:string}>('SELECT id,checkout_token FROM ra_renewals WHERE order_id=$1',[id]);failMail=false;mails.length=0;let resume!:()=>void;mailHold=new Promise<void>(resolve=>resume=resolve);const reached=new Promise<void>(resolve=>mailEntered=resolve);const sending=runRenewals('2030-05-18');await reached;const paid=await request(`agent-checkout/renewal/${r.id}?token=${r.checkout_token}`,{sourceId:'offline-credit',consent:true});resume();await sending;await runRenewals('2030-05-18');check('correspondence','older decline delivery cannot acknowledge a newly queued receipt',paid.status===200&&mails.length===2&&mails[0].html.includes('renewal charge was declined')&&mails[1].subject.startsWith('Registered agent service renewed'),{paid,mails});}

 {const id=await company('2030-06-01');await db.query("UPDATE orders SET card_status='missing',square_card_id=NULL WHERE id=$1",[id]);await runRenewals('2030-06-02');check('correspondence','overdue unpaid reminder does not ask payment by past date',mails.some(m=>m.html.includes('now overdue'))&&!mails.some(m=>m.html.includes('so please pay it by')),mails);}

}
if(process.argv.includes('--child'))await child();else if(import.meta.main)await batch41BillingChecks((label,ok,detail)=>{console.log(JSON.stringify({label,ok,detail},null,2));if(!ok)process.exitCode=1;});
