import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {PDFDocument} from '@cantoo/pdf-lib';
type Check=(ok:boolean,label:string,detail?:unknown)=>void;
export async function batch07Checks(check:Check){
 const dir=mkdtempSync(join(tmpdir(),'batch07-'));
 try{const p=Bun.spawn(['bun',import.meta.filename,'--child'],{cwd:process.cwd(),env:{...process.env,E2E_OFFLINE:'1',VERCEL:'',DEV_PG_DIR:join(dir,'db'),DEV_STORAGE_DIR:join(dir,'files'),ADMIN_PASSWORD:'dev-admin'},stdout:'pipe',stderr:'pipe'});const [out,err,code]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);const rows=out.split('\n').filter(x=>x.startsWith('BATCH07:')).map(x=>JSON.parse(x.slice(8)));for(const r of rows)check(r.ok,r.label,r.detail);if(code||rows.length<10)throw new Error(`Batch07 fixture failed ${code}: ${err}\n${out}`);}finally{rmSync(dir,{recursive:true,force:true});}
}
async function child(){
 const {app}=await import('./app'),{getDb}=await import('./db'),{newToken}=await import('./crypto'),{env}=await import('./env');
 const {runRenewals,addDays,fulfillPaidRenewal}=await import('./renewals'),{testHooks}=await import('./shared');
 const {defaultFormData}=await import('../src/components/forms/florida-llc/defaults'),{buildPayload}=await import('../src/components/forms/florida-llc/buildPayload');
 const db=await getDb(),query=db.query.bind(db);const check:Check=(ok,label,detail)=>console.log('BATCH07:'+JSON.stringify({ok,label,detail:ok?undefined:detail}));
 const proof=(await (await app.request('/api/dev/env-summary')).json()).data;if(!proof?.offline||Object.values(proof.externals).some(Boolean))throw new Error('Isolation not proven');
 let mailFail=false;const mails:{html:string;to:string[];subject:string}[]=[];env.RESEND_API_KEY='fixture-only';
 globalThis.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{if(String(input)!=='https://api.resend.com/emails')throw new Error('External request refused');if(mailFail)return Response.json({message:'planned notice failure'},{status:503});mails.push(JSON.parse(String(init?.body)));return Response.json({id:'fixture'});}) as typeof fetch;
 const admin=newToken(),client=crypto.randomUUID();await query("INSERT INTO clients(id,email,name) VALUES($1,'seven@example.test','Seven Client')",[client]);await query("INSERT INTO sessions(token_hash,is_admin,expires_at) VALUES($1,true,now()+interval '1 day')",[admin.tokenHash]);
 const req=(path:string,body?:object|FormData)=>app.request('/api'+path,{method:body===undefined?'GET':'POST',headers:{Cookie:`fpsllc_admin=${admin.token}`,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});
 const order=async(status='formed',own=false)=>{const id=crypto.randomUUID(),d=structuredClone(defaultFormData);Object.assign(d,{desiredLlcName:'Seven Company',llcDesignator:'LLC',clientFirstName:'Seven',clientLastName:'Client',clientEmail:'seven@example.test',registeredAgentChoice:own?'SELF':'SERVICE',raRenewalCardConsent:true});const p=buildPayload(d);await query("INSERT INTO orders(id,client_id,contact_name,contact_email,package,llc_name,payload,service_fee_cents,state_fees_cents,total_cents,status,paid_at,square_card_id,square_customer_id,card_status,card_last4) VALUES($1,$2,'Seven Client','seven@example.test','NEW','Seven Company LLC',$3,9900,0,9900,$4,$5,$6,$7,$8,'1111')",[id,status==='pending_payment'?null:client,JSON.stringify(p),status,status==='pending_payment'?null:new Date().toISOString(),status==='pending_payment'?null:'card-fixture',status==='pending_payment'?null:'cust-fixture',status==='pending_payment'?null:'on_file']);return id;};
 const rows=(id:string)=>query<Record<string,unknown>>('SELECT * FROM ra_renewals WHERE order_id=$1 ORDER BY created_at',[id]);
 const attempt=async(label:string,f:()=>Promise<void>)=>{await query('UPDATE orders SET ra_renewal_date=NULL');mails.length=0;mailFail=false;testHooks.declineNextRenewal='';try{await f();}catch(e){check(false,label,String(e));}finally{db.query=query;mailFail=false;}};
 const renewal='2026-08-01';
 const scheduled=async()=>{const id=await order();await query('UPDATE orders SET ra_renewal_date=$2 WHERE id=$1',[id,renewal]);return id;};
 await attempt('batch28 194: scheduled notice precedes cancellation deadline by forty days',async()=>{const id=await scheduled();await runRenewals(addDays(renewal,-71));const early=await rows(id);await runRenewals(addDays(renewal,-70));const sent=await rows(id);check(!early.length&&sent[0]?.status==='notice_sent'&&mails.some(m=>m.html.includes('July 2, 2026')),'batch28 194: scheduled notice precedes cancellation deadline by forty days',{early,sent,mails});});
 await attempt('batch07 N1.12: failed notices remain pending and block automatic charging',async()=>{const id=await scheduled();mailFail=true;await runRenewals(addDays(renewal,-45));await new Promise(r=>setTimeout(r,40));const before=await rows(id);await runRenewals(addDays(renewal,-15));const failed=await rows(id);mailFail=false;await runRenewals(addDays(renewal,-14));await runRenewals(addDays(renewal,-13));const late=await rows(id);check(before[0]?.status==='notice_pending'&&!before[0]?.notice_sent_at&&!failed[0]?.charged_at&&late[0]?.billing_hold===true&&!late[0]?.charged_at,'batch07 N1.12: failed notices remain pending and block automatic charging',{before,failed,late});});
 await attempt('batch07 195: payment attempts are counted and idempotent',async()=>{const id=await scheduled();await runRenewals(addDays(renewal,-60));await runRenewals(addDays(renewal,-45));testHooks.declineNextRenewal='INSUFFICIENT_FUNDS';await runRenewals(addDays(renewal,-15));const first=await rows(id);testHooks.declineNextRenewal='INSUFFICIENT_FUNDS';await runRenewals(addDays(renewal,-13));const second=await rows(id);await runRenewals(addDays(renewal,-11));const third=await rows(id);check(first[0]?.retries===1&&second[0]?.retries===2&&!second[0]?.retry_after&&third[0]?.status==='declined','batch07 195: payment attempts are counted and idempotent',{first,second,third});const text=mails.filter(m=>/declined/i.test(m.subject)).at(-1)?.html??'';check(!/try the card once more/i.test(text)&&/immediately|right away|now/i.test(text),'batch07 199: no false retry promises',text);});
 await attempt('batch07 196: receipts describe payments accurately',async()=>{const id=await scheduled();const [row]=await query<{id:string}>("INSERT INTO ra_renewals(order_id,renewal_date,amount_cents,status,charge_due) VALUES($1,$2,9900,'declined',$2) RETURNING id",[id,renewal]);await fulfillPaidRenewal(row.id,'receipt-fixture','credit');await new Promise(r=>setTimeout(r,50));const receipt=mails.at(-1)?.html??'';await Promise.all([fulfillPaidRenewal(row.id,'receipt-fixture','credit'),fulfillPaidRenewal(row.id,'receipt-fixture','credit')]);const [o]=await query<{date:string}>('SELECT ra_renewal_date::text AS date FROM orders WHERE id=$1',[id]);check(/received/i.test(receipt)&&!/(we charged|charged your card)/i.test(receipt)&&o.date==='2027-08-01','batch07 196: receipts describe payments accurately',{receipt,o});});
 await attempt('batch07 28: annual billing and cancellation resignation policy',async()=>{const id=await scheduled();await query("UPDATE orders SET ra_cancellation_requested_at='2026-06-01T12:00:00Z' WHERE id=$1",[id]);await runRenewals(addDays(renewal,-15));await runRenewals(renewal);const r=await rows(id);const [o]=await query<{data:Record<string,unknown>}>('SELECT to_jsonb(o) AS data FROM orders o WHERE id=$1',[id]);check(r[0]?.purpose==='resignation'&&r[0]?.amount_cents===9900&&r[0]?.status==='charged'&&String(o.data.ra_resignation_due).startsWith(renewal)&&String(o.data.ra_renewal_date).startsWith(renewal)&&!o.data.ra_resignation_submitted,'batch07 28: annual billing and cancellation resignation policy',{r,o});});
 await attempt('batch07 46: prepaid attempted purchases are refused only for our agent service',async()=>{const id=await order('pending_payment');const blocked=await req('/dev/simulate-payment',{orderId:id,card:'prepaid'});const [o]=await query<{status:string;client_id:string|null}>('SELECT status,client_id FROM orders WHERE id=$1',[id]);const other=await order('pending_payment',true);const allowed=await req('/dev/simulate-payment',{orderId:other,card:'prepaid'});const retry=await req('/dev/simulate-payment',{orderId:id,card:'credit'});check(blocked.status===400&&o.status==='pending_payment'&&!o.client_id&&allowed.status===200&&retry.status===200,'batch07 46: prepaid attempted purchases are refused only for our agent service',{blocked:blocked.status,o,allowed:allowed.status,retry:retry.status});});
 await attempt('batch07 47: consent and a saved eligible card are both required',async()=>{const id=await order('pending_payment');const blocked=await req('/dev/simulate-payment',{orderId:id,card:'wallet'});const [o]=await query<{status:string;client_id:string|null}>('SELECT status,client_id FROM orders WHERE id=$1',[id]);const nc=await order('pending_payment');await query("UPDATE orders SET payload=jsonb_set(payload,'{registeredAgent,renewalCardConsent}','false') WHERE id=$1",[nc]);const refused=await req('/dev/simulate-payment',{orderId:nc,card:'credit'});check(blocked.status===400&&!o.client_id&&o.status==='pending_payment'&&refused.status===400,'batch07 47: consent and a saved eligible card are both required',{blocked:blocked.status,o,refused:refused.status});});
 const doc=await PDFDocument.create();doc.addPage();const pdf=await doc.save();const upload=()=>{const f=new FormData();f.set('articles',new File([new Uint8Array(pdf)],'articles.pdf',{type:'application/pdf'}));f.append('psd',new File([new Uint8Array(pdf)],'psd.pdf',{type:'application/pdf'}));f.append('psdSeries','[]');return f;};
 await attempt('batch07 208: replacement uploads preserve dates',async()=>{const id=await order();await query("UPDATE orders SET formed_at='2026-01-02T12:00:00Z',ra_renewal_date='2027-02-03' WHERE id=$1",[id]);const r=await req(`/admin/orders/${id}/formation-documents`,upload());const [o]=await query<{formed:string;renews:string}>('SELECT formed_at::text AS formed,ra_renewal_date::text AS renews FROM orders WHERE id=$1',[id]);check(r.status===200&&o.formed.startsWith('2026-01-02')&&o.renews==='2027-02-03','batch07 208: replacement uploads preserve dates',{status:r.status,body:await r.json(),o});});
 await attempt('batch07 212: appointment effective date starts the service year',async()=>{const id=await order('paid');const r=await req(`/admin/orders/${id}/formation-documents`,upload());const [before]=await query<{date:string|null}>('SELECT ra_renewal_date::text AS date FROM orders WHERE id=$1',[id]);const recorded=await req(`/admin/orders/${id}/agent`,{action:'appointment',date:'2026-02-03'});const [after]=await query<{date:string|null}>('SELECT ra_renewal_date::text AS date FROM orders WHERE id=$1',[id]);check(r.status===200&&before.date===null&&recorded.status===200&&after.date==='2027-02-03','batch07 212: appointment effective date starts the service year',{upload:r.status,before,recorded:recorded.status,after});}); await attempt('batch07 payment interruptions preserve one provider identity',async()=>{
  const {payAgentTarget,agentCheckoutLink}=await import('./ra-checkout');const mailFetch=globalThis.fetch;
  env.SQUARE_ACCESS_TOKEN='synthetic-fixture';let loseCapture=true,creates=0,captures=0;const payments=new Map<string,{id:string;status:string;card_details:{card:{prepaid_type:string}}}>();const sequence:string[]=[];
  globalThis.fetch=(async(input:RequestInfo|URL,init?:RequestInit)=>{
   const u=new URL(String(input));if(u.origin==='https://api.resend.com')return mailFetch(input,init);if(!['https://connect.squareupsandbox.com','https://connect.squareup.com'].includes(u.origin))throw new Error('External request refused');
   const body=init?.body?JSON.parse(String(init.body)):{};sequence.push(u.pathname);
   if(u.pathname==='/v2/payments'){if(body.autocomplete!==false||body.delay_action!=='CANCEL')throw new Error('Unsafe capture configuration');let p=payments.get(body.idempotency_key);if(!p){creates++;p={id:'pay-'+body.idempotency_key,status:'APPROVED',card_details:{card:{prepaid_type:body.source_id==='fixture-prepaid'?'PREPAID':'NOT_PREPAID'}}};payments.set(body.idempotency_key,p);}return Response.json({payment:p});}
   if(u.pathname==='/v2/customers')return Response.json({customer:{id:'cust'}});
   if(u.pathname==='/v2/cards')return Response.json({card:{id:'ccof:fixture',last_4:'1111',card_brand:'VISA',prepaid_type:'NOT_PREPAID'}});
   const p=[...payments.values()].find(p=>u.pathname.includes(p.id));if(!p)throw new Error('Unknown synthetic payment');
   if(u.pathname.endsWith('/complete')){if(p.status!=='COMPLETED')captures++;p.status='COMPLETED';if(loseCapture){loseCapture=false;throw new Error('Response lost after capture');}}
   if(u.pathname.endsWith('/cancel'))p.status='CANCELED';return Response.json({payment:p});
  }) as typeof fetch;
  try{
   const id=await order('pending_payment');const first=await payAgentTarget('order',id,{token:'fixture-card'});const retry=await payAgentTarget('order',id,{token:'different-token-must-not-charge'});const again=await payAgentTarget('order',id,{token:'third-token'});
   check(!first.ok&&first.code==='UNRESOLVED'&&retry.ok&&again.ok&&creates===1&&captures===1&&sequence.indexOf('/v2/cards')<sequence.findIndex(x=>x.endsWith('/complete')),'batch07 payment interruptions preserve one provider identity',{first,retry,again,creates,captures,sequence});
   const id2=await order('pending_payment');const concurrent=await Promise.all([payAgentTarget('order',id2,{token:'fixture-card'}),payAgentTarget('order',id2,{token:'fixture-card'})]);check(concurrent.some(r=>r.ok)&&creates===2&&captures===2,'batch07 concurrent submissions make one purchase',{concurrent,creates,captures});
   const id3=await order('pending_payment');const prepaid=await payAgentTarget('order',id3,{token:'fixture-prepaid'});check(!prepaid.ok&&prepaid.code==='PREPAID_CARD'&&captures===2&&[...payments.values()].at(-1)?.status==='CANCELED','batch07 real provider refusal cancels authorization before capture',{prepaid,captures});
   const link=await agentCheckoutLink('order',id3);const wrong=await req(`/agent-checkout/order/${id3}?token=wrong`);check(wrong.status===404&&new URL(link).searchParams.get('token')!.length>=32,'batch07 payment links reject the wrong capability',{status:wrong.status});
  }finally{env.SQUARE_ACCESS_TOKEN='';globalThis.fetch=mailFetch;}
 });
 await attempt('batch07 missing email credentials leave the notice pending',async()=>{
  const id=await scheduled(),prior={key:env.RESEND_API_KEY,prod:env.isProd};
  try{env.RESEND_API_KEY='';env.isProd=true;await runRenewals(addDays(renewal,-60));const r=await rows(id);check(r[0]?.status==='notice_pending'&&!r[0]?.notice_sent_at,'batch07 missing email credentials leave the notice pending',r);}finally{env.RESEND_API_KEY=prior.key;env.isProd=prior.prod;}
 });
 await attempt('batch07 missing Square credentials cannot simulate a live payment',async()=>{
  const {payAgentTarget}=await import('./ra-checkout');const id=await order('pending_payment');const prior={offline:env.OFFLINE,prod:env.isProd};
  try{env.OFFLINE=false;env.isProd=true;const result=await payAgentTarget('order',id,{token:'fixture-card'});const [o]=await query<{status:string;paid_at:unknown}>('SELECT status,paid_at FROM orders WHERE id=$1',[id]);check(!result.ok&&result.code==='UNAVAILABLE'&&o.status==='pending_payment'&&!o.paid_at,'batch07 missing Square credentials cannot simulate a live payment',{result,o});}finally{env.OFFLINE=prior.offline;env.isProd=prior.prod;}
 });
 await attempt('batch07 resignation records email and statutory mailing separately',async()=>{
  const id=await scheduled();await query("UPDATE orders SET ra_cancellation_requested_at='2026-06-01T12:00:00Z' WHERE id=$1",[id]);await runRenewals(renewal);
  const future=await req(`/admin/orders/${id}/agent`,{action:'submitted',date:'2099-01-01'});const submitted=await req(`/admin/orders/${id}/agent`,{action:'submitted',date:renewal});
  const copy=new FormData();copy.set('file',new File([new Uint8Array(pdf)],'resignation.pdf',{type:'application/pdf'}));mailFail=true;const failed=await req(`/admin/orders/${id}/agent-copy`,copy);mailFail=false;const sent=await req(`/admin/orders/${id}/agent-copy`,new FormData());
  const filed=await req(`/admin/orders/${id}/agent`,{action:'filed',date:'2026-08-02'});const mailed=await req(`/admin/orders/${id}/agent`,{action:'mailed',date:'2026-08-01'});const state=(await (await req(`/admin/orders/${id}/agent`)).json()).data;
  check(future.status===400&&submitted.status===200&&failed.status===503&&sent.status===200&&filed.status===200&&mailed.status===200&&!!state.ra_resignation_emailed_at&&state.ra_ended_date.startsWith('2026-09-02'),'batch07 resignation records email and statutory mailing separately',{future:future.status,submitted:submitted.status,failed:failed.status,sent:sent.status,filed:filed.status,mailed:mailed.status,state});
 });

}
if(process.argv.includes('--child'))await child();else if(import.meta.main){let fails=0;await batch07Checks((ok,label,detail)=>{console.log(JSON.stringify({ok,label,detail}));if(!ok)fails++;});process.exit(fails?1:0);}
