/* eslint-disable @typescript-eslint/no-explicit-any -- Isolated SQL and provider fault-injection fixtures. */
import {mkdirSync,writeFileSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
const E=process.env.CHECK_OUTPUT_DIR||mkdtempSync(tmpdir()+'/chunk3-corrections-'),R=process.env.AUDIT_ROOT||resolve(import.meta.dir,'..'),run='check',temp=E+'/fixtures/office-'+run+'-'+Date.now();mkdirSync(temp,{recursive:true});
Object.assign(process.env,{E2E_OFFLINE:'1',VERCEL:'',DEV_PG_DIR:temp+'/db',DEV_STORAGE_DIR:temp+'/files',DEV_MIRROR_DIR:temp+'/mirror',ADMIN_PASSWORD:'fixture'});
const {app}=await import(R+'/server/app.ts'),{env}=await import(R+'/server/env.ts'),{getDb}=await import(R+'/server/db.ts'),{newToken}=await import(R+'/server/crypto.ts');
const db:any=await getDb(),rawQuery=db.query.bind(db),proof=(await(await app.request('/api/dev/env-summary')).json()).data;
if(!proof.offline||Object.values(proof.externals).some(Boolean))throw Error('Offline isolation failed');
const rows:any[]=[],mail:any[]=[],outside:string[]=[];let mailMode='ok';
globalThis.fetch=(async(input:any,init:any={})=>{const url=String(input);if(url!=='https://api.resend.com/emails'){outside.push(url);throw Error('NETWORK REFUSED '+url)}const m=JSON.parse(init.body);if(mailMode==='fail')return new Response('Fixture outage',{status:503});mail.push(m);if(mailMode==='lost')throw Error('Fixture accepted but response lost');return Response.json({id:'mail-'+mail.length})}) as typeof fetch;env.RESEND_API_KEY='fixture';
function check(id:string,ok:boolean,observed:any={}){rows.push({id,result:ok?'pass':'fail',observed});console.log('CASE:'+JSON.stringify(rows.at(-1)));writeFileSync(E+'/office-'+run+'.json',JSON.stringify({proof,temp,rows},null,2));}
async function test(id:string,fn:()=>Promise<void>){try{await rawQuery('DELETE FROM rate_limits');await fn()}catch(e){check(id,false,{harnessError:String(e),stack:(e as Error).stack})}finally{db.query=rawQuery;mailMode='ok'}}
const admin=newToken(),user=newToken(),other=newToken(),client=crypto.randomUUID(),client2=crypto.randomUUID();
await db.query("INSERT INTO clients(id,name,email) VALUES($1,'Current Client','current@example.test'),($2,'Other Client','other@example.test')",[client,client2]);
await db.query("INSERT INTO sessions(token_hash,is_admin,expires_at) VALUES($1,true,now()+interval '1 day')",[admin.tokenHash]);for(const [t,c]of[[user,client],[other,client2]])await db.query("INSERT INTO sessions(token_hash,client_id,expires_at) VALUES($1,$2,now()+interval '1 day')",[t.tokenHash,c]);
const cookies={admin:'fpsllc_admin='+admin.token,client:'fpsllc_session='+user.token,other:'fpsllc_session='+other.token,none:''};
async function req(path:string,body?:any,actor:keyof typeof cookies='admin',method?:string){const multipart=body instanceof FormData;const r=await app.request('/api/'+path,{method:method||(body===undefined?'GET':'POST'),headers:{Cookie:cookies[actor],...(!multipart?{'content-type':'application/json'}:{})},body:body===undefined?undefined:multipart?body:JSON.stringify(body)});const bytes=new Uint8Array(await r.arrayBuffer());let data:any;try{data=JSON.parse(new TextDecoder().decode(bytes))}catch{data={bytes:bytes.length,head:new TextDecoder().decode(bytes.slice(0,8))}}return{status:r.status,body:data,bytes,headers:Object.fromEntries(r.headers)}}
const {PDFDocument}=await import(R+'/node_modules/@cantoo/pdf-lib');const pdf=await PDFDocument.create();pdf.addPage([300,300]);const pdfBytes=await pdf.save();
function form(fields:any={},files:string[]=['file'],bytes:Uint8Array=pdfBytes){const f=new FormData();for(const[k,v]of Object.entries(fields))f.set(k,String(v));for(const k of files)f.set(k,new File([new Uint8Array(bytes)],k+'.pdf',{type:'application/pdf'}));return f}
async function company(opts:any={}){const id=crypto.randomUUID();await db.query(`INSERT INTO orders(id,client_id,contact_name,contact_email,package,llc_name,payload,service_fee_cents,state_fees_cents,total_cents,status,paid_at,formed_at) VALUES($1,$2,'Historical Client','old@example.test',$3,$4,$5,49900,12500,62400,$6,$7,$8)`,[id,opts.client||client,opts.package||'NEW',opts.name||'Office Audit LLC',JSON.stringify({filingPath:opts.package||'NEW',series:opts.series||[],optionalDocuments:opts.certs?{certificateOfStatus:true,certifiedCopy:true}:{},registeredAgent:{choice:'SELF'},...(opts.payload||{})}),opts.status||'paid',opts.unpaid?null:new Date().toISOString(),opts.status==='formed'?new Date().toISOString():null]);return id}
const docs=async(co:string)=>await db.query('SELECT * FROM documents WHERE order_id=$1 ORDER BY created_at,id',[co]);
const correctedDoc=await PDFDocument.create();correctedDoc.addPage([321,456]);const correctedBytes=await correctedDoc.save();


const current=async(co:string)=>(await docs(co)).filter((x:any)=>!x.deleted_at);
const detail=async(co:string)=>(await req('admin/orders/'+co)).body.data;
const commitSql=(sql:string)=>sql.includes("retired AS (")&&sql.includes("UPDATE documents SET deleted_at=now()");
async function seed(status='filed',signed=true){const co=await company({status:'filed',payload:{certifications:{articlesSignedBy:signed?'SERVICE':'SELF'}}});const r=await req('admin/orders/'+co+'/articles',form({documentNumber:'L26000123456'},['articles']));if(r.status!==200)throw Error('Initial articles failed '+JSON.stringify(r));if(status==='formed')await rawQuery("UPDATE orders SET status='formed',formed_at=now() WHERE id=$1",[co]);return co}
const payload=(d:any,number='L26000987654',pdf=correctedBytes,replace=false)=>form({documentNumber:number,documentId:d.articlesCorrection.documentId,revision:d.articlesCorrection.revision,...replace?{replaceAttempt:d.articlesCorrection.pendingOperation}:{}},['articles'],pdf);
const change=(co:string,d:any,n?:string,p?:Uint8Array,replace=false)=>req('admin/orders/'+co+'/correct-articles',payload(d,n,p,replace));
async function validatePair(co:string,number:string){const dd=await current(co),a=dd.find((x:any)=>x.kind==='articles'),s=dd.find((x:any)=>x.kind==='statement');const dl=await req('portal/documents/'+s?.id+'/download',undefined,'client');const file=temp+'/statement.pdf';writeFileSync(file,dl.bytes);const executable=Bun.which('pdftotext');if(!executable)throw Error('This PDF regression requires pdftotext on PATH.');const extracted=spawnSync(executable,[file,'-'],{encoding:'utf8'});return{ok:!!a&&!!s&&a.meta.documentNumber===number&&s.meta.documentNumber===number&&dl.status===200&&extracted.status===0&&extracted.stdout.includes(number),dd,a,s,dl,text:extracted.stdout}}
for(const status of ['filed','formed'])await test('published-'+status,async()=>{
 const co=await seed(status),d=await detail(co),prior=await current(co),n=mail.length;
 const first=await change(co,d);const v=await validatePair(co,'L26000987654');const repeat=await change(co,d);const denied=await req('admin/orders/'+co+'/correct-articles',payload(d),'client');const foreign=await req('portal/documents/'+v.a?.id+'/download',undefined,'other');const history=(await docs(co)).filter((x:any)=>x.deleted_at);
 check(status+'-correct-pair-one-notice-history-access',first.status===200&&repeat.status===200&&v.ok&&mail.length===n+1&&history.length===2&&denied.status===401&&foreign.status===404,{first,repeat,status:(await rawQuery('SELECT status FROM orders WHERE id=$1',[co]))[0],newDocs:v.dd.length,history:history.length,mail:mail.slice(n),statementText:v.text});
 check(status+'-history-bytes-retained',(await Promise.all(prior.map((x:any)=>import(R+'/server/storage.ts').then(s=>s.readStoredFile(x.storage_key))))).every(Boolean));
 const latest=await detail(co),second=await change(co,latest,'L26000111222',pdfBytes);const stale=await change(co,d,'L26000999888',pdfBytes);check(status+'-next-correction-and-stale-refusal',second.status===200&&stale.status===409&&(await validatePair(co,'L26000111222')).ok,{second:second.status,stale:stale.status});
});
for(const point of ['intent','articles-metadata','statement-metadata','commit','lost-commit'])await test('fault-'+point,async()=>{
 const co=await seed(),d=await detail(co),original=await current(co);let fired=false;
 db.query=async(sql:string,args:any[])=>{const match=point==='intent'?sql.includes('INSERT INTO office_operations(id,kind,target_id,input_hash,payload)')&&sql.includes('articles-correction'):point==='articles-metadata'||point==='statement-metadata'?sql.includes('SET files=files||')&&args?.[2]===(point==='articles-metadata'?'articles':'statement'):commitSql(sql);if(!fired&&match){fired=true;if(point==='lost-commit')await rawQuery(sql,args);throw Error('Injected '+point)}return rawQuery(sql,args)};
 const fail=await change(co,d);db.query=rawQuery;const between=await current(co);const retry=await change(co,d),v=await validatePair(co,'L26000987654');check('fault-'+point+'-retry-pair',fired&&fail.status===500&&retry.status===200&&v.ok&&(point==='lost-commit'||between.map((x:any)=>x.id).join()===original.map((x:any)=>x.id).join()),{fired,fail:fail.status,retry:retry.status,body:retry.body,between:between.map((x:any)=>x.id)});
});
await test('failed-correction-replaced',async()=>{const co=await seed(),d=await detail(co);let fired=false;db.query=async(sql:string,args:any[])=>{if(!fired&&commitSql(sql)){fired=true;throw Error('stop')}return rawQuery(sql,args)};await change(co,d);db.query=rawQuery;const pending=await detail(co);const wrong=await change(co,pending,'L26000333222',pdfBytes);const fixed=await change(co,pending,'L26000333222',pdfBytes,true);check('failed-correction-replaced',fired&&wrong.status===409&&fixed.status===200&&(await validatePair(co,'L26000333222')).ok,{wrong:wrong.status,fixed:fixed.status,body:fixed.body})});
await test('overlap',async()=>{const co=await seed(),d=await detail(co);let enter!:()=>void,resume!:()=>void;const arrived=new Promise<void>(r=>enter=r),released=new Promise<void>(r=>resume=r);let held=false;db.query=async(sql:string,args:any[])=>{if(!held&&sql.includes('SET files=files||')){held=true;enter();await released}return rawQuery(sql,args)};const first=change(co,d);await arrived;const second=await change(co,d);const fileOnly=await req('admin/documents/'+d.articlesCorrection.documentId+'/replace',form());resume();const win=await first;db.query=rawQuery;check('overlap-single-winner-and-old-replace-refused',win.status===200&&second.status===409&&fileOnly.status===409&&(await current(co)).length===2,{win:win.status,second:second.status,fileOnly:fileOnly.status});});
await test('notification-only-retry',async()=>{const co=await seed(),d=await detail(co),n=mail.length;mailMode='fail';const saved=await change(co,d);const dd=await detail(co);mailMode='ok';const before=(await current(co)).map((x:any)=>x.id).join();const sent=await req('admin/documents/'+dd.articlesCorrection.noticeId+'/resend-notice',{});const again=await req('admin/documents/'+dd.articlesCorrection.noticeId+'/resend-notice',{});check('notice-only-retry-once',saved.status===200&&!saved.body.data.notified&&sent.body.data?.notified&&again.body.data?.notified&&mail.length===n+1&&before===(await current(co)).map((x:any)=>x.id).join(),{saved:saved.body,sent:sent.body,again:again.body,mail:mail.length-n});});
await test('self-signed',async()=>{const co=await seed('filed',false),d=await detail(co);const r=await change(co,d);check('self-signed-no-statement',r.status===200&&(await current(co)).length===1,{status:r.status});});
await test('recovery-history',async()=>{const co=await seed(),d=await detail(co);await change(co,d);const {backupFiles,BACKUP_TABLES}=await import(R+'/server/backup.ts');const tables:any={};for(const t of BACKUP_TABLES)tables[t]=await rawQuery('SELECT * FROM '+t);const files=backupFiles(tables);const dd=await docs(co);check('backup-includes-current-and-history-pair',dd.length===4&&dd.every((d:any)=>files.some((f:any)=>f.storageKey===d.storage_key)),{documents:dd.length,allIncluded:dd.map((d:any)=>files.some((f:any)=>f.storageKey===d.storage_key))});const {runDbBackup}=await import(R+'/server/backup.ts'),{readObject}=await import(R+'/server/storage.ts'),{gunzipSync}=await import('node:zlib');const backup=await runDbBackup();const dump=backup.complete?JSON.parse(gunzipSync((await readObject('backups/'+backup.key))!).toString()):null;check('published-backup-retains-history-rows',backup.complete&&dd.every((d:any)=>dump.tables.documents.some((row:any)=>row.id===d.id)),{complete:backup.complete,historyRows:dump?.tables.documents.filter((row:any)=>row.order_id===co&&row.meta?.officeHistory).length});});
check('no-outside-network',outside.length===0,{outside});
writeFileSync(E+'/office-'+run+'.json',JSON.stringify({proof,temp,rows},null,2));process.exit(rows.some(r=>r.result==='fail')?1:0);
