import {activeDeadline} from './operation-deadline';
import { ensureDeletionMirror, appendDeletionMirror, readRecoveryJournal, recordDocumentCopy } from './backup-deletions';
/** An append-only deletion marker outside database snapshots prevents an old
 * restore from reviving a client's deleted document. Cleanup is retryable. */
import { getDb } from './db';
import {cleanupSupersededOfficeFiles} from './office-operation';
import { putObject, readObject, listObjects, deletionPath, removeStoredFile } from './storage';
import { deleteMirror, documentMirrorPath } from './dropbox';
export interface Deletion {serviceId?:string;storageKey:string;documentId:string;mirrorPath:string;requestedAt:string;extraMirrorPaths?:string[];reason?:'client'|'superseded'|'office'}
export async function deletionJournal(): Promise<Deletion[]> {
 const keys=await listObjects('deletions/'), out:Deletion[]=[];
 for(const key of keys){const b=await readObject(key);if(!b)throw new Error('Deletion journal changed during read');out.push(JSON.parse(b.toString()));}return out;
}
export async function requestDocumentDeletion(id:string,clientId:string,reason:'client'|'superseded'='client'):Promise<boolean>{return deleteDocument(id,clientId,reason,false)}
/** Only the authenticated office certificate route calls this entry point. */
export async function requestCertificateDeletion(id:string):Promise<{found:boolean;pending:boolean}>{
 const db=await getDb();const [d]=await db.query<{client_id:string;kind:string}>('SELECT client_id,kind FROM documents WHERE id=$1',[id]);
 if(!d||!['certificate-of-status','certified-copy'].includes(d.kind))return {found:false,pending:false};
 await deleteDocument(id,d.client_id,'office',true);
 const [state]=await db.query<{pending:boolean}>('SELECT COALESCE(bool_or(completed_at IS NULL),true) AS pending FROM document_deletions WHERE document_id=$1',[id]);
 return {found:true,pending:state?.pending??true};
}
async function deleteDocument(id:string,clientId:string,reason:'client'|'superseded'|'office',officeCertificate:boolean):Promise<boolean>{
 const db=await getDb();
 const [d]=await db.query<{id:string;storage_key:string;mirror_path:string|null;title:string;kind:string;llc_name:string|null;email:string|null;meta:{sensitive?:boolean}|null}>(`SELECT d.*,o.llc_name,c.email FROM documents d LEFT JOIN orders o ON o.id=d.order_id AND o.client_id=d.client_id LEFT JOIN clients c ON c.id=d.client_id WHERE d.id=$1 AND d.client_id=$2`,[id,clientId]);
 if(!d || !(d.meta?.sensitive||(officeCertificate&&['certificate-of-status','certified-copy'].includes(d.kind))))return false;
 const record:Deletion={storageKey:d.storage_key,documentId:d.id,mirrorPath:d.mirror_path||documentMirrorPath(d),requestedAt:new Date().toISOString(),reason};
 if(!(await db.query("SELECT id FROM backup_progress WHERE id='deletion-journal'")).length)await ensureDeletionMirror(await deletionJournal());
 await registerOfficeDocumentHistory(id,clientId);
 await appendDeletionMirror(record);
 const path=deletionPath(d.storage_key);
 if(!await readObject(path)){
  try{await putObject(path,Buffer.from(JSON.stringify(record)));}
  catch(e){
   // A concurrent delete can create the same immutable marker first. Accept
   // only a readable marker for this exact document and key; preserve it.
   const saved=await readObject(path);
   if(!saved)throw e;
   const existing=JSON.parse(saved.toString()) as Deletion;
   if(existing.storageKey!==record.storageKey||existing.documentId!==record.documentId)throw e;
  }
 }
 // Register every controlled-copy decision generated by the atomic client deletion.
 const journal=await readRecoveryJournal();
 const services=new Set(journal.packages.filter(p=>p.id===id||p.priorDocumentId===id).map(p=>p.serviceId));
 const officeServices=new Set((journal.copies??[]).filter(p=>p.documentId===id).map(p=>p.serviceId).filter(Boolean));
 const ids=new Set([id,...journal.packages.filter(p=>services.has(p.serviceId)).map(p=>p.id),...(journal.copies??[]).filter(p=>p.serviceId&&officeServices.has(p.serviceId)).map(p=>p.documentId)]);
 for(const decision of journal.records.filter(r=>ids.has(r.documentId))){if(!await readObject(deletionPath(decision.storageKey)))await putObject(deletionPath(decision.storageKey),Buffer.from(JSON.stringify(decision)),true);await registerDeletion(decision);}
 await retryDocumentDeletions({documentIds:[...ids],budgetMs:20000});return true;
}
// Deletion supersedes an availability observation for the exact stored revision.
// Filtering by key preserves other slots and a successor sharing a document id.
const retainedHistorySql=`COALESCE((SELECT jsonb_object_agg(h.key,h.value)
 FROM jsonb_each(COALESCE(payload->'historyRecovery','{}'::jsonb)) h
 WHERE h.value->>'storageKey' IS DISTINCT FROM $1),'{}'::jsonb)`;
const hasDeletedHistorySql=`EXISTS(SELECT 1 FROM jsonb_each(COALESCE(payload->'historyRecovery','{}'::jsonb)) h WHERE h.value->>'storageKey'=$1)`;
export async function clearDeletedOfficeHistory(storageKey:string):Promise<void>{
 const db=await getDb();
 await db.query(`WITH forgotten AS (
  UPDATE office_operations SET payload=jsonb_set(payload,'{historyRecovery}',${retainedHistorySql})
  WHERE ${hasDeletedHistorySql} RETURNING id
 ) UPDATE documents SET meta=COALESCE(meta,'{}'::jsonb)-'historyRecovery'
 WHERE storage_key=$1 AND meta ? 'historyRecovery'`,[storageKey]);
}
async function registerDeletion(r:Deletion){
 const db=await getDb();
 // One statement: a lost registration reply must not leave the portal row
 // visible, or leave regeneration enabled for a logically deleted document.
 await db.query(`WITH registered AS (
   INSERT INTO document_deletions(storage_key,document_id,mirror_path,requested_at)
   VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING RETURNING storage_key
 ), hidden AS (
   UPDATE documents SET deleted_at=COALESCE(deleted_at,$4),meta=COALESCE(meta,'{}'::jsonb)-'historyRecovery' WHERE storage_key=$1 RETURNING id
 ), forgotten AS (
   UPDATE office_operations SET payload=jsonb_set(payload,'{historyRecovery}',${retainedHistorySql})
   WHERE ${hasDeletedHistorySql} RETURNING id
 ) UPDATE service_orders SET ein_secret=NULL,
   details=COALESCE(details,'{}'::jsonb)||jsonb_build_object('documentDeletedAt',$6::text)
   WHERE $5::text IS DISTINCT FROM 'superseded' AND details->>'documentId'=$2::text`,
  [r.storageKey,r.documentId,r.mirrorPath,r.requestedAt,r.reason??null,r.requestedAt]);
}
export async function retryDocumentDeletions(options:{documentId?:string;documentIds?:string[];budgetMs?:number;limit?:number;deadline?:number}={}):Promise<{pending:number}>{
 const deadline=Math.min(options.deadline??Date.now()+(options.budgetMs??30000),activeDeadline());
 const db=await getDb();if(Date.now()<deadline)await cleanupSupersededOfficeFiles(db,{deadline});
 const ids=options.documentIds??(options.documentId?[options.documentId]:null);
 const limit=Math.max(1,Math.min(options.limit??50,100));
 if(!(await db.query("SELECT id FROM backup_progress WHERE id='deletion-journal'")).length)await ensureDeletionMirror(await deletionJournal());
 const journal=await readRecoveryJournal();
 // Journal reads verify the complete durable record. Provider deletion work
 // visits a bounded round-robin batch, including previously completed deletes
 // so arbitrarily late uploads are removed on a later pass.
 const all=journal.records.filter(r=>!ids||ids.includes(r.documentId)).sort((a,b)=>a.storageKey.localeCompare(b.storageKey));
 const cursorKey=ids?'deletion-cleanup:'+ids.slice().sort().join(','):'deletion-cleanup';
 const [cursor]=await db.query<{cursor:string|null}>('SELECT cursor FROM backup_progress WHERE id=$1',[cursorKey]);
 const after=all.filter(r=>r.storageKey>(cursor?.cursor??''));
 const batch=(after.length?after:all).slice(0,limit);
 for(const r of batch){
  if(Date.now()>=deadline)break;
  try{
   if(!await readObject(deletionPath(r.storageKey)))await putObject(deletionPath(r.storageKey),Buffer.from(JSON.stringify(r)),true);
   await registerDeletion(r);
   await removeStoredFile(r.storageKey);for(const path of new Set([r.mirrorPath,...(r.extraMirrorPaths??[])]))if(path)await deleteMirror(path);
   await db.query('UPDATE document_deletions SET completed_at=now(),error=NULL WHERE storage_key=$1',[r.storageKey]);
  }catch(e){await db.query('UPDATE document_deletions SET completed_at=NULL,error=$2 WHERE storage_key=$1',[r.storageKey,String(e)]);}
  await db.query('INSERT INTO backup_progress(id,cursor) VALUES($1,$2) ON CONFLICT(id) DO UPDATE SET cursor=EXCLUDED.cursor',[cursorKey,r.storageKey]);
 }
 const [n]=await db.query<{n:string}>('SELECT count(*) AS n FROM document_deletions WHERE completed_at IS NULL');
 const known=new Set((await db.query<{storage_key:string}>('SELECT storage_key FROM document_deletions')).map(r=>r.storage_key));
 return {pending:Number(n.n)+journal.records.filter(r=>!known.has(r.storageKey)).length};
}

/** Backfill pre-registry revisions from their retained operation history. The
 * durable registry survives database loss and a deletion catches all copies. */
export async function registerOfficeDocumentHistory(id:string,clientId:string):Promise<void>{
 const db=await getDb();
 await ensureDeletionMirror(await deletionJournal());
 const rows=await db.query<{id:string;target_id:string;files:Record<string,{id:string;key:string;title:string;kind:string;mirrorPath?:string}>;llc_name:string}>(`SELECT op.id,op.target_id,op.files,so.llc_name FROM office_operations op JOIN service_orders so ON so.id=op.target_id WHERE so.client_id=$2 AND (op.kind='service' OR op.kind LIKE 'service-history:%') AND op.target_id IN (
 SELECT linked.target_id FROM office_operations linked WHERE linked.kind='service' OR linked.kind LIKE 'service-history:%'
 INTERSECT SELECT linked.target_id FROM office_operations linked WHERE linked.result->>'documentId'=$1 OR linked.payload->>'previousDocumentId'=$1 OR EXISTS(SELECT 1 FROM jsonb_each(linked.files) f WHERE f.value->>'id'=$1))`,[id,clientId]);
 for(const row of rows)for(const [slot,f] of Object.entries(row.files))await recordDocumentCopy({serviceId:row.target_id,documentId:f.id,storageKey:f.key,extraMirrorPaths:[`/OfficeOperations/${row.id}/${slot}`],mirrorPath:f.mirrorPath||documentMirrorPath({id:f.id,title:f.title,kind:f.kind,llc_name:row.llc_name,storage_key:f.key})});
 const [d]=await db.query<{id:string;storage_key:string;mirror_path:string|null;title:string;kind:string;llc_name:string|null;email:string|null}>(`SELECT d.*,o.llc_name,c.email FROM documents d LEFT JOIN orders o ON o.id=d.order_id LEFT JOIN clients c ON c.id=d.client_id WHERE d.id=$1 AND d.client_id=$2`,[id,clientId]);
 if(d)await recordDocumentCopy({documentId:id,storageKey:d.storage_key,mirrorPath:d.mirror_path||documentMirrorPath(d)});
}
