/**
 * Amendment to Operating Agreement (Adam, 12 Sep 2026): "a standard amendment
 * form with recitals that refer to the amendment provisions in the OA and then
 * an area for them to add changes or to make changes set forth in the attached
 * exhibit. Then signed by all members as required by the OA with the
 * appropriate signature blocks."
 *
 * The ninth master, templates-oa-amendment.md, is filled from the STORED
 * inputs of the agreement being amended, so the parties who sign the
 * amendment are the parties who signed the agreement — every Member (both
 * spouses of a marital unit), and the Manager's acknowledgment on the
 * manager-managed forms, whose s. 15.1(c) / s. 12.1(b) bar an amendment from
 * imposing new obligations on the Manager without the Manager's written
 * consent. Every sentence is the master's; this file chooses and repeats.
 */
import { readFileSync } from "node:fs";
import amendmentTemplateRaw from "./templates-oa-amendment.md";
import { chooseNumber, expandRepeat, titleCaseHolding, OA_TEMPLATE_VERSION, type OaInputs } from "./oa";

function loadTemplate(v: string): string {
  return v.includes("AMENDMENT NO.") ? v : readFileSync(v, "utf8");
}
const amendmentTemplate = loadTemplate(amendmentTemplateRaw as string);

export interface AmendmentInputs {
  /** Per company, counting up from 1; printed in the title and the preamble. */
  number: number;
  /** Human format, "September 12, 2026". */
  effectiveDate: string;
  /** The changes typed in the portal, or set forth in an exhibit the client
   *  attaches to the printed amendment. */
  mode: "typed" | "attached";
  text?: string;
}

/** `<!-- if:KEY -->…<!-- /if -->` outside a repeat block: kept when the
 *  condition holds, dropped otherwise. Inside a repeat block expandRepeat
 *  resolves the same marker per row. */
function resolveIf(s: string, key: string, keep: boolean): string {
  const re = new RegExp(`<!--\\s*if:${key}\\s*-->([\\s\\S]*?)<!--\\s*/if\\s*-->`, "g");
  if (!re.test(s)) throw new Error(`Amendment template marker missing: if:${key}`);
  return s.replace(re, (_m, inner: string) => (keep ? inner : ""));
}

function must(haystack: string, needle: string, label: string): void {
  if (!haystack.includes(needle)) throw new Error(`Amendment template marker missing: ${label}`);
}

/** The Section of the agreement that governs its own amendment: s. 15.1 in
 *  the four multi-member forms, s. 12.1 in the four single-member forms. Read
 *  from the masters on 12 Sep 2026, all eight: "may be amended only by a
 *  written instrument signed by **all** Members" (15.1) / "signed by the
 *  Member" (12.1). */
export function amendmentSection(version: OaInputs["version"]): "15.1" | "12.1" {
  return version === "single" || version === "single-s" || version === "member-single" || version === "member-single-s"
    ? "12.1"
    : "15.1";
}

/** The typed changes, one paragraph per line the client typed. The renderer
 *  needs a blank line between paragraphs; a single Enter in a text box does
 *  not give one. */
export function paragraphsOf(text: string): string {
  return text
    .replace(/\r\n?/g, "\n")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .join("\n\n");
}

export function assembleAmendment(oa: OaInputs, am: AmendmentInputs): { markdown: string; title: string } {
  const isSingle =
    oa.version === "single" || oa.version === "single-s" ||
    oa.version === "member-single" || oa.version === "member-single-s";
  const isMemberManaged =
    oa.version === "member" || oa.version === "member-s" ||
    oa.version === "member-single" || oa.version === "member-single-s";
  if (am.mode === "typed" && !(am.text ?? "").trim()) throw new Error("Amendment: typed changes are empty");
  if (!Number.isInteger(am.number) || am.number < 1) throw new Error("Amendment: number must be 1 or more");

  let s = amendmentTemplate;
  const co = oa.companyName;
  const title = `Amendment No. ${am.number} to Operating Agreement`;

  // ---- footer: lifted, filled, re-appended ----
  const FOOTER_LINE = "*[TITLE] of [COMPANY NAME], LLC — generated by MyFloridaSeriesLLC · Master [EDITION]*";
  must(s, FOOTER_LINE, "master footer line");
  s = s.replace(FOOTER_LINE, "").trimEnd() + "\n";

  // ---- conditions the master spells both ways ----
  s = resolveIf(s, "managed", !isMemberManaged);
  s = resolveIf(s, "restated", oa.amendedRestated);
  s = resolveIf(s, "typed", am.mode === "typed");
  s = resolveIf(s, "attached", am.mode === "attached");
  s = chooseNumber(s, "member", isSingle);

  // ---- slots ----
  must(s, "[AMENDMENT NUMBER]", "amendment number");
  s = s.split("[AMENDMENT NUMBER]").join(String(am.number));
  must(s, "[COMPANY NAME], LLC", "company name");
  s = s.split("[COMPANY NAME], LLC").join(co);
  s = s.split("[COMPANY NAME]").join(co);
  must(s, "[AMENDMENT DATE]", "amendment date");
  s = s.split("[AMENDMENT DATE]").join(am.effectiveDate);
  must(s, "[AGREEMENT DATE]", "agreement date");
  s = s.split("[AGREEMENT DATE]").join(oa.effectiveDate);
  must(s, "[AMENDMENT SECTION]", "amendment section");
  s = s.split("[AMENDMENT SECTION]").join(amendmentSection(oa.version));
  // ---- signatures: the same blocks the agreement uses ----
  s = expandRepeat(
    s,
    "signatory",
    oa.members.flatMap((m) => {
      const signers = m.signatories ?? [m.name];
      return signers.map((n, i) => ({
        "[UNIT]": signers.length > 1 && i === 0 ? m.name : "",
        "[HOLDING]": signers.length > 1 && i === 0 && m.jointHolding ? `as ${titleCaseHolding(m.jointHolding)}` : "",
        "[SIGNATORY NAME]": n,
      }));
    }),
    "amendment member signatures",
  );
  if (!isMemberManaged) {
    const managerNames = (oa.managerNames ?? []).map((n) => n.trim()).filter(Boolean);
    if (managerNames.length === 0) throw new Error("Amendment: at least one manager is required");
    s = chooseNumber(s, "manager", managerNames.length === 1);
    s = expandRepeat(s, "manager", managerNames.map((n) => ({ "[MANAGER NAME]": n })), "amendment manager signatures");
  }

  const footer = FOOTER_LINE
    .replace("[TITLE]", title)
    .replace("[COMPANY NAME], LLC", co)
    .replace("[EDITION]", OA_TEMPLATE_VERSION);
  s = s.trimEnd() + "\n\n" + footer + "\n";
  s = s.replace(/\n{3,}/g, "\n\n");

  // Every slot filled and every marker resolved — checked BEFORE the client's
  // typed changes go in, so a bracketed phrase of theirs cannot fail the check.
  const leftover = (s.match(/\[[A-Z][A-Z ()/.']*\]/g) ?? []).filter((x) => !(am.mode === "typed" && x === "[AMENDMENT TEXT]"));
  if (leftover.length > 0) throw new Error(`Amendment: unfilled slot(s): ${[...new Set(leftover)].join(", ")}`);
  if (/<!--/.test(s)) throw new Error("Amendment: template marker left in the document");
  if (am.mode === "typed") {
    must(s, "[AMENDMENT TEXT]", "amendment text");
    s = s.replace("[AMENDMENT TEXT]", () => paragraphsOf(am.text ?? ""));
  }

  return { markdown: s, title: `${title} — ${co}` };
}
