/**
 * Amendment to Operating Agreement (Adam, 12 Sep 2026): recitals that refer to
 * the agreement's own amendment provision, the changes typed or set forth in
 * an attached exhibit, and the signature blocks the agreement uses — every
 * Member, and the Manager's acknowledgment on the manager-managed forms.
 */
import { assembleAmendment, amendmentSection, paragraphsOf } from "./oa-amendment";
import type { OaInputs } from "./oa";

let failures = 0;
let checks = 0;
function check(name: string, ok: boolean, got?: unknown): void {
  checks++;
  if (ok) console.log(`✅ ${name}`);
  else { failures++; console.log(`❌ ${name}${got !== undefined ? ` — got ${JSON.stringify(got)?.slice(0, 300)}` : ""}`); }
}

const base: OaInputs = {
  version: "multi",
  companyName: "ACME Holdings, LLC",
  principalAddress: "100 Ocean Dr, Miami, FL 33139",
  managerNames: ["Adam Kirwan"],
  effectiveDate: "August 5, 2026",
  amendedRestated: false,
  priorAgreementDate: null,
  members: [
    { name: "Adam Kirwan", address: "100 Ocean Dr, Miami, FL 33139", percentage: 50, contribution: "$500", todBeneficiary: "" },
    {
      name: "Casey Gatecheck and Blair Gatecheck",
      address: "200 Bay St, Miami, FL 33131",
      percentage: 50,
      contribution: "$500",
      todBeneficiary: "",
      signatories: ["Casey Gatecheck", "Blair Gatecheck"],
      jointHolding: "tenants by the entirety",
    },
  ],
  series: [],
};

// ---- multi-member, manager-managed, typed changes ----
const typed = assembleAmendment(base, { number: 1, effectiveDate: "September 12, 2026", mode: "typed", text: "Section 4.7 is deleted.\nSection 6.2 is amended to read: \"Capital calls require the consent of all Members.\"" });
const md = typed.markdown;
check("title names the number and the company", typed.title === "Amendment No. 1 to Operating Agreement — ACME Holdings, LLC", typed.title);
check("heading carries the number", md.includes("# AMENDMENT NO. 1\n# TO OPERATING AGREEMENT\n## OF\n## ACME Holdings, LLC"), md.slice(0, 120));
check("preamble names the members and the manager's acknowledgment", md.includes('is made effective as of September 12, 2026, by the undersigned members (each a "Member" and collectively the "Members"), and is acknowledged by the undersigned Manager.'), md.match(/is made effective[^\n]*/)?.[0]);
check("recital A names the agreement and its date", md.includes('A. The Company is governed by the Operating Agreement of the Company effective as of August 5, 2026 (the "Agreement").'), md.match(/A\. The Company[^\n]*/)?.[0]);
check("recital B cites s. 15.1 and all Members", md.includes("B. Section 15.1 of the Agreement provides that the Agreement may be amended only by a written instrument signed by all Members."), md.match(/B\. Section[^\n]*/)?.[0]);
check("recital C and the operative words are plural", md.includes("C. The Members wish to amend the Agreement as set forth in this Amendment.") && md.includes("NOW, THEREFORE, the Members amend the Agreement as follows:"));
check("typed changes are printed, one paragraph per line", md.includes("**1. Amendments to the Agreement.** The Agreement is amended as follows:\n\nSection 4.7 is deleted.\n\nSection 6.2 is amended to read: \"Capital calls require the consent of all Members.\"\n\n**2. Effect of Amendment.**"), md.match(/\*\*1\. Amendments[\s\S]*?\*\*2\./)?.[0]);
check("the attached-exhibit sentence is absent when the changes are typed", !md.includes("Exhibit A"));
check("effect clause is verbatim", md.includes("**2. Effect of Amendment.** Except as amended by this Amendment, the Agreement remains in full force and effect. Capitalized terms have the meanings given in the Agreement. This Amendment is effective on the date stated above."));
check("signatures start a new page", md.includes("[[pagebreak]]\n\n## SIGNATURES"));
check("IN WITNESS WHEREOF is plural", md.includes("IN WITNESS WHEREOF, the undersigned have executed this Amendment effective as of the date(s) set forth below.\n\n**MEMBERS:**"));
check("every member signs, the couple headed by both names and their holding", md.includes("**Casey Gatecheck and Blair Gatecheck**\nas Tenants by the Entirety\n\n_____________________________\nCasey Gatecheck\nDate: _____________________________\n\n_____________________________\nBlair Gatecheck\nDate:"), md.match(/\*\*MEMBERS:\*\*[\s\S]*$/)?.[0]);
check("the solo member signs on a line of their own", md.includes("**MEMBERS:**\n\n_____________________________\nAdam Kirwan\nDate: _____________________________"));
check("the manager acknowledges", md.includes("**ACKNOWLEDGED AND AGREED BY MANAGER:**\n\n_____________________________\nAdam Kirwan, Manager\nDate: _____________________________"), md.match(/ACKNOWLEDGED[\s\S]*$/)?.[0]);
check("footer names the amendment, the company, and the edition", /\*Amendment No\. 1 to Operating Agreement of ACME Holdings, LLC — generated by MyFloridaSeriesLLC · Master First Edition — August 2026\*\n$/.test(md), md.slice(-160));
check("no slot or marker is left", !/\[[A-Z][A-Z ()/.']*\]/.test(md) && !md.includes("<!--"), md.match(/\[[A-Z][A-Z ()/.']*\]|<!--[^>]*-->/g));

// ---- two managers, attached exhibit ----
const two = assembleAmendment({ ...base, managerNames: ["Adam Kirwan", "Tom Jones"] }, { number: 2, effectiveDate: "October 1, 2026", mode: "attached" });
check("attached: the exhibit sentence stands in for the typed changes", two.markdown.includes("**1. Amendments to the Agreement.** The Agreement is amended as follows:\n\nThe Agreement is amended as set forth in Exhibit A attached to this Amendment.\n\n**2. Effect of Amendment.**"), two.markdown.match(/\*\*1\. Amendments[\s\S]*?\*\*2\./)?.[0]);
check("two managers acknowledge under the plural heading", two.markdown.includes("**ACKNOWLEDGED AND AGREED BY MANAGERS:**\n\n_____________________________\nAdam Kirwan, Manager\nDate: _____________________________\n\n_____________________________\nTom Jones, Manager"), two.markdown.match(/ACKNOWLEDGED[\s\S]*$/)?.[0]);
check("attached: the number is 2 throughout", two.title.startsWith("Amendment No. 2 ") && two.markdown.includes("# AMENDMENT NO. 2\n") && two.markdown.includes("THIS AMENDMENT NO. 2 TO OPERATING AGREEMENT"));

// ---- single member, member-managed, amended and restated agreement ----
const single: OaInputs = {
  ...base,
  version: "member-single",
  managerNames: [],
  amendedRestated: true,
  members: [{ name: "Maria Lopez", address: "500 Bay Street, Miami, FL 33131", percentage: 100, contribution: "$1,000", todBeneficiary: "" }],
};
const sm = assembleAmendment(single, { number: 1, effectiveDate: "September 12, 2026", mode: "typed", text: "Section 3.1 is amended to add a second Protected Series." }).markdown;
check("single: preamble names the sole member and no manager", sm.includes('by the undersigned sole member (the "Member").') && !sm.includes("acknowledged by"), sm.match(/is made effective[^\n]*/)?.[0]);
check("single: recital A names the Amended and Restated agreement", sm.includes('A. The Company is governed by the Amended and Restated Operating Agreement of the Company effective as of August 5, 2026 (the "Agreement").'), sm.match(/A\. The Company[^\n]*/)?.[0]);
check("single: recital B cites s. 12.1 and the Member", sm.includes("B. Section 12.1 of the Agreement provides that the Agreement may be amended only by a written instrument signed by the Member."), sm.match(/B\. Section[^\n]*/)?.[0]);
check("single: recital C and the operative words are singular", sm.includes("C. The Member wishes to amend the Agreement as set forth in this Amendment.") && sm.includes("NOW, THEREFORE, the Member amends the Agreement as follows:"));
check("single: IN WITNESS WHEREOF is singular and the heading is MEMBER", sm.includes("IN WITNESS WHEREOF, the undersigned has executed this Amendment effective as of the date(s) set forth below.\n\n**MEMBER:**\n\n_____________________________\nMaria Lopez\nDate: _____________________________"), sm.match(/IN WITNESS[\s\S]*$/)?.[0]);
check("single member-managed: no manager block", !sm.includes("ACKNOWLEDGED") && !sm.includes(", Manager"));
check("single: no slot or marker is left", !/\[[A-Z][A-Z ()/.']*\]/.test(sm) && !sm.includes("<!--"), sm.match(/\[[A-Z][A-Z ()/.']*\]|<!--[^>]*-->/g));

// ---- single member, manager-managed: the manager still acknowledges ----
const smm = assembleAmendment({ ...single, version: "single-s", managerNames: ["Maria Lopez"], amendedRestated: false }, { number: 3, effectiveDate: "September 12, 2026", mode: "attached" }).markdown;
check("single manager-managed: s. 12.1 and the manager's acknowledgment", smm.includes("B. Section 12.1 of the Agreement") && smm.includes("and is acknowledged by the undersigned Manager.") && smm.includes("**ACKNOWLEDGED AND AGREED BY MANAGER:**\n\n_____________________________\nMaria Lopez, Manager"));
check("single manager-managed: recital A names the Operating Agreement, not restated", smm.includes("governed by the Operating Agreement of the Company effective"));

// ---- the eight forms route to the right section ----
check("sections: the four multi-member forms cite 15.1", (["multi", "s", "member", "member-s"] as const).every((v) => amendmentSection(v) === "15.1"));
check("sections: the four single-member forms cite 12.1", (["single", "single-s", "member-single", "member-single-s"] as const).every((v) => amendmentSection(v) === "12.1"));

// ---- the client's bracketed words do not fail the slot check ----
const brackets = assembleAmendment(base, { number: 1, effectiveDate: "September 12, 2026", mode: "typed", text: "Section 13.2 is replaced with [RESERVED]." }).markdown;
check("a client's own bracketed phrase is printed as typed", brackets.includes("Section 13.2 is replaced with [RESERVED]."));

// ---- refusals ----
let threw = "";
try { assembleAmendment(base, { number: 1, effectiveDate: "September 12, 2026", mode: "typed", text: "   " }); } catch (e) { threw = String(e); }
check("typed changes that are blank are refused", /typed changes are empty/.test(threw), threw);
threw = "";
try { assembleAmendment({ ...base, managerNames: [] }, { number: 1, effectiveDate: "September 12, 2026", mode: "attached" }); } catch (e) { threw = String(e); }
check("a manager-managed agreement with no manager is refused", /at least one manager/.test(threw), threw);
check("paragraphsOf: Windows line endings and blank lines", paragraphsOf("a\r\n\r\n  b \nc") === "a\n\nb\n\nc", paragraphsOf("a\r\n\r\n  b \nc"));

console.log(`\n${checks} checks, ${failures} failures`);
if (failures > 0) process.exit(1);
